structure(list(url = "https://app.crunch.io/api/", status_code = 401L, 
    headers = structure(list(date = "Wed, 07 Oct 2020 22:05:35 GMT", 
        `content-type` = "application/json", `content-length` = "191", 
        server = "nginx", `content-encoding` = "gzip", vary = "Accept-Encoding", 
        allow = "GET, HEAD, OPTIONS, POST", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 07 Oct 2020 22:05:35 GMT", 
            `content-type` = "application/json", `content-length` = "191", 
            server = "nginx", `content-encoding` = "gzip", vary = "Accept-Encoding", 
            allow = "GET, HEAD, OPTIONS, POST", `x-xss-protection` = "1; mode=block", 
            `strict-transport-security` = "max-age=31536000; includeSubDomains", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"status\": \"401 Unauthorized\", \"urls\": {\"login_url\": \"https://app.crunch.io/api/public/login/\", \"password_reset_url\": \"https://app.crunch.io/api/public/password_reset/\", \"otp_authorize\": \"https://app.crunch.io/api/otp/authorize\", \"public_url\": \"https://app.crunch.io/api/public/\", \"otp_login\": \"https://app.crunch.io/api/otp/login\", \"email_change_url\": \"https://app.crunch.io/api/public/change_email/\", \"password_change_url\": \"https://app.crunch.io/api/public/password_change/\", \"collect_inquires\": \"https://app.crunch.io/api/public/inquire/\"}}"), 
    date = structure(1602108335, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.002639, 
    connect = 0.00264, pretransfer = 0.002826, starttransfer = 0.203583, 
    total = 0.203707)), class = "response")
