structure(list(url = "/logout/", status_code = 204L, headers = structure(list(
    allow = "GET, HEAD, OPTIONS", `content-type` = "application/json;charset=utf-8", 
    date = "Sat, 24 Feb 2018 23:27:12 GMT", server = "nginx", 
    `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
    connection = "keep-alive"), .Names = c("allow", "content-type", 
"date", "server", "set-cookie", "vary", "connection"), class = c("insensitive", 
"list")), all_headers = list(structure(list(status = 204L, version = "HTTP/1.1", 
    headers = structure(list(allow = "GET, HEAD, OPTIONS", `content-type` = "application/json;charset=utf-8", 
        date = "Sat, 24 Feb 2018 23:27:12 GMT", server = "nginx", 
        `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
        connection = "keep-alive"), .Names = c("allow", "content-type", 
    "date", "server", "set-cookie", "vary", "connection"), class = c("insensitive", 
    "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = ".crunch.io", flag = TRUE, 
        path = "/", secure = FALSE, expiration = structure(1551050831, class = c("POSIXct", 
        "POSIXt")), name = "token", value = "REDACTED"), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw(""), date = structure(1519514832, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = structure(c(0, 3e-05, 
    3.2e-05, 9e-05, 0.172387, 0.172437), .Names = c("redirect", 
    "namelookup", "connect", "pretransfer", "starttransfer", 
    "total"))), .Names = c("url", "status_code", "headers", "all_headers", 
"cookies", "content", "date", "times"), class = "response")
