structure(list(url = "/api/projects/264e6b/", status_code = 201L, 
    headers = structure(list(date = "Thu, 21 Nov 2024 16:31:43 GMT", 
        `content-type` = "application/json;charset=utf-8", `content-length` = "0", 
        location = "/api/projects/ac0645/", server = "CherryPy/18.9.0", 
        allow = "DELETE, GET, HEAD, OPTIONS, PATCH, POST", vary = "Cookie, Accept-Encoding", 
        `x-frame-options` = "DENY", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/2", 
        headers = structure(list(date = "Thu, 21 Nov 2024 16:31:43 GMT", 
            `content-type` = "application/json;charset=utf-8", 
            `content-length` = "0", location = "/api/projects/ac0645/", 
            server = "CherryPy/18.9.0", allow = "DELETE, GET, HEAD, OPTIONS, PATCH, POST", 
            vary = "Cookie, Accept-Encoding", `x-frame-options` = "DENY", 
            `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1732206703, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 1.9e-05, 
    connect = 0, pretransfer = 0.000148, starttransfer = 0.377591, 
    total = 0.377627)), class = "response")
