structure(list(url = "/sources/", status_code = 201L, headers = structure(list(
    allow = "GET, HEAD, OPTIONS, POST", `content-encoding` = "gzip", 
    `content-type` = "application/json;charset=utf-8", date = "Sat, 24 Feb 2018 04:33:13 GMT", 
    location = "/sources/8c91bf/", server = "nginx", `set-cookie` = "REDACTED", 
    vary = "Cookie, Accept-Encoding", `x-timing` = "", `content-length` = "86", 
    connection = "keep-alive"), .Names = c("allow", "content-encoding", 
"content-type", "date", "location", "server", "set-cookie", "vary", 
"x-timing", "content-length", "connection"), class = c("insensitive", 
"list")), all_headers = list(structure(list(status = 201L, version = "HTTP/1.1", 
    headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
        `content-encoding` = "gzip", `content-type` = "application/json;charset=utf-8", 
        date = "Sat, 24 Feb 2018 04:33:13 GMT", location = "/sources/8c91bf/", 
        server = "nginx", `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
        `x-timing` = "", `content-length` = "86", connection = "keep-alive"), .Names = c("allow", 
    "content-encoding", "content-type", "date", "location", "server", 
    "set-cookie", "vary", "x-timing", "content-length", "connection"
    ), class = c("insensitive", "list"))), .Names = c("status", 
"version", "headers"))), cookies = structure(list(domain = ".crunch.io", 
    flag = TRUE, path = "/", secure = FALSE, expiration = structure(1550982793, class = c("POSIXct", 
    "POSIXt")), name = "token", value = "REDACTED"), .Names = c("domain", 
"flag", "path", "secure", "expiration", "name", "value"), row.names = c(NA, 
-1L), class = "data.frame"), content = as.raw(c(0x7b, 0x22, 0x65, 
0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3a, 0x20, 0x22, 0x73, 
0x68, 0x6f, 0x6a, 0x69, 0x3a, 0x76, 0x69, 0x65, 0x77, 0x22, 0x2c, 
0x20, 0x22, 0x73, 0x65, 0x6c, 0x66, 0x22, 0x3a, 0x20, 0x22, 0x2f, 
0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x22, 0x7d)), 
    date = structure(1519446793, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = structure(c(0, 3.7e-05, 3.8e-05, 
    0.000136, 0.000148, 0.89591), .Names = c("redirect", "namelookup", 
    "connect", "pretransfer", "starttransfer", "total"))), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times"), class = "response")
