structure(list(url = "/api/public/login/", status_code = 204L, 
    headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
        `content-type` = "application/json;charset=utf-8", date = "Fri, 02 Mar 2018 17:28:19 GMT", 
        server = "nginx", `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
        connection = "keep-alive"), .Names = c("allow", "content-type", 
    "date", "server", "set-cookie", "vary", "connection"), class = c("insensitive", 
    "list")), all_headers = list(structure(list(status = 204L, 
        version = "HTTP/1.1", headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
            `content-type` = "application/json;charset=utf-8", 
            date = "Fri, 02 Mar 2018 17:28:19 GMT", server = "nginx", 
            `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
            connection = "keep-alive"), .Names = c("allow", "content-type", 
        "date", "server", "set-cookie", "vary", "connection"), class = c("insensitive", 
        "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = ".crunch.io", flag = TRUE, 
        path = "/", secure = FALSE, expiration = structure(1551547699, class = c("POSIXct", 
        "POSIXt")), name = "token", value = "REDACTED"), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw(""), date = structure(1520011699, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = structure(c(0, 0.023661, 
    0.259972, 0.67039, 0.875597, 0.875642), .Names = c("redirect", 
    "namelookup", "connect", "pretransfer", "starttransfer", 
    "total"))), .Names = c("url", "status_code", "headers", "all_headers", 
"cookies", "content", "date", "times"), class = "response")
