---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The Crunch web app and the Crucnh package are both built around a [REST API](http://docs.crunch.io/), this allows users to interact with very large survey datasets because most of the heavy computation is done on the Crunch servers, and not on the users computer. Most of the design patterns used in Crunch flow from this basic architecture. 

### Catalogs

When you open a dataset in the Crunch web app, what happens is that the app sends an HTTP request to the Crunch server for information about that dataset. For instance it gets the dataset description, the and a list of variables contained within that dataset, but the actual data is store don the server and not sent to the app. The app only loads information about variables which are actually going to be displayed on the screen, which is why very large datasets load so quickly. For instance you might have a million entries in a numeric variable, but the web app only asks the server for the summary statistics it needs to display the variable card. 

This kind of minimally neccessary information are stored in objects called `Shoji Catalogs`, which are often referred to as catalogs. For instance there is a `VariableCatalog` which has information about a dataset's variables, `ProjectCatalog` which has information about a project, and a `UserCatalog` which stores user information. You can think of catalogs just like the Sears Catalog: they are lists of things and descriptions about those things, but they are not the things themselves. You might flip through a catalog looking for the couch, but you need to make a special order if you actually want the couch delivered. 

The R package relates to the Crunch API in more or less the same manner as the web app. When you load a Crunch dataset from the server you are not typically loading the actual data, but instead you are loading a catalog representation of that dataset which is stored in a list. This object includes things like the dataset identifier, the variable names and classes, and the dataset dimensions, but the actual data stays on the server. When calculations are perfomed on that data what happens is that an HTTP request is sent to the server, the server calculates the answer, and the results are sent back to the R session. This is what allows you to calculate statistics on objects which don't fit in memory, the calculations are done remotely and only the result of that calculation is sent back to you.

### Getters and Setters

Many Crunch functions both retrieve information from the server and allow the user to set information. For instance if you want to retrieve a list of datasets associated with a project you could call the [datasets()] function like this: 
```
proj <- projects()[["Project name"]]
datasets(proj)
```

What happens under the hood when you run this code is that R sends an HTTP request to the server asking for the datasets associated with a particular project. This is the `getter` side of the `datasets()` function. However, the function also allows the user to change the datasets associated with that function using tyhe assignment operator. 

```
ds <- loadDataset(mydatasets[["Dataset name"]]) -->
datasets(proj) <- ds
```

Internally there is actually a second method `datasets()<-` which takes the value on the right hand side of the `<-` operator and posts that value to the datasets attribute of the project catalog. The projects catalog will then update to reflect that a dataset belongs to a particular catalog, and that will be reflected in the web app. 