structure(list(url = "/api/public/login/", status_code = 401L, 
    headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
        `content-encoding` = "gzip", `content-type` = "application/json", 
        date = "Mon, 14 May 2018 17:11:35 GMT", server = "nginx", 
        vary = "Accept-Encoding", `content-length` = "168", connection = "keep-alive"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
            `content-encoding` = "gzip", `content-type` = "application/json", 
            date = "Mon, 14 May 2018 17:11:35 GMT", server = "nginx", 
            vary = "Accept-Encoding", `content-length` = "168", 
            connection = "keep-alive"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"status\": \"401 Unauthorized\", \"urls\": {\"login_url\": \"/api/public/login/\", \"password_reset_url\": \"/api/public/password_reset/\", \"public_url\": \"/api/public/\", \"email_change_url\": \"/api/public/change_email/\", \"password_change_url\": \"/api/public/password_change/\", \"collect_inquires\": \"/api/public/inquire/\"}}"), 
    date = structure(1526317895, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.062907, 
    connect = 0.169207, pretransfer = 0.417769, starttransfer = 0.533782, 
    total = 0.533963)), class = "response")
