structure(list(url = "/public/login/", status_code = 204L, headers = structure(list(
    allow = "GET, HEAD, OPTIONS, POST", `content-type` = "application/json;charset=utf-8", 
    date = "Sat, 24 Feb 2018 04:33:05 GMT", server = "nginx", 
    `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
    connection = "keep-alive"), .Names = c("allow", "content-type", 
"date", "server", "set-cookie", "vary", "connection"), class = c("insensitive", 
"list")), all_headers = list(structure(list(status = 204L, version = "HTTP/1.1", 
    headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
        `content-type` = "application/json;charset=utf-8", date = "Sat, 24 Feb 2018 04:33:05 GMT", 
        server = "nginx", `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
        connection = "keep-alive"), .Names = c("allow", "content-type", 
    "date", "server", "set-cookie", "vary", "connection"), class = c("insensitive", 
    "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = ".crunch.io", flag = TRUE, 
        path = "/", secure = FALSE, expiration = structure(1550982785, class = c("POSIXct", 
        "POSIXt")), name = "token", value = "REDACTED"), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = c(NA, 
    -1L), class = "data.frame"), content = raw(0), date = structure(1519446785, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = structure(c(0, 4.1e-05, 
    4.3e-05, 0.000104, 0.230668, 0.230718), .Names = c("redirect", 
    "namelookup", "connect", "pretransfer", "starttransfer", 
    "total"))), .Names = c("url", "status_code", "headers", "all_headers", 
"cookies", "content", "date", "times"), class = "response")
