mapcty <- c(NA, "Orange", "Mecklenburg", NA, "Lee", "Arapahoe", "Alachua",
"Lafayette", NA, "Manitowoc", NA, "Outagamie", "Seminole", "Osceola",
NA, "Waukesha", "Pierce", "Johnston", NA, "Guilford", "Orange",
NA, "El Paso", NA, "Outagamie", "Waukesha", "Buncombe", "Clear Creek",
"Arapahoe", NA, NA, NA, NA, NA, "Waukesha", "Dane", NA, "Polk",
"Wake", "Waukesha", "Dane", "Waukesha", NA, "Denver", "Weld",
NA, NA, "Larimer", NA, "Washburn", NA, "Milwaukee", "Marinette",
NA, NA, "Johnston", "Dane", "Brown", "Manitowoc", "Buncombe",
"Milwaukee", "Boulder", "Larimer", NA, "Douglas", NA, "Douglas",
NA, "Mesa", "Waukesha", NA, "Gaston", "Buncombe", "Sheboygan",
"Brunswick", "Fond du Lac", "Kenosha", "Forsyth", NA, NA, "Waukesha",
"Davie", "La Plata", "Waukesha", "Waukesha", "Buncombe", "Pamlico",
NA, "Catawba", NA, NA, "Douglas", "Jackson", "El Paso", "Waukesha",
"Franklin", "Racine", NA, NA, NA, NA, "New Hanover", "Dane",
"Mecklenburg", "Delta", "Mecklenburg", "Orange", NA, "Adams",
"Broward", "Orange", "Eagle", NA, NA, NA, NA, NA, "Vernon", NA,
NA, "Walworth", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Collier",
"Alachua", NA, "Sarasota", "Volusia", NA, "Lee", "Escambia",
"Palm Beach", NA, "Broward", "Duval", NA, NA, "Hillsborough",
NA, NA, "Orange", "Orange", "Hillsborough", "Pinellas", "Seminole",
"Hillsborough", "Sarasota", "Hillsborough", "Lake", NA, "Lee",
"Miami-Dade", "Hillsborough", NA, "Orange", "Polk", "Escambia",
"Escambia", "Clay", NA, "Palm Beach", NA, "Lee", NA, "Polk",
"Leon", "Hernando", NA, "Alachua", "Caldwell", "Lee", "Broward",
"Palm Beach", "Sampson", NA, NA, "Sumter", "Davidson", "Wake",
"Orange", "Volusia", "Escambia", NA, "Palm Beach", NA, "Pasco",
"Brevard", "El Paso", NA, NA, NA, NA, NA, "Arapahoe", "Portage",
"Manatee", NA, NA, "New Hanover", "Palm Beach", NA, "Charlotte",
"Denver", "Pasco", NA, NA, "Orange", "Mecklenburg", NA, "Broward",
"Otero", "La Crosse", "Pasco", "Marion", "Miami-Dade", "Orange",
"Iredell", "Sumter", "Indian River", "Manatee", "Hillsborough",
"St. Johns", "Pasco", "Pasco", "St. Lucie", "Hillsborough", "Charlotte",
"St. Johns", "Hillsborough", "Palm Beach", "Pasco", "Broward",
"Miami-Dade", "Duval", "Broward", "Citrus", "Manatee", "Cleveland",
"Pasco", "Lake", "Flagler", "Highlands", "Transylvania", "Miami-Dade",
"Polk", "Manatee", "Escambia", "Indian River", "Bay", "Broward",
"Alamance", "Charlotte", "Hillsborough", "Sarasota", "Wake",
"Miami-Dade", "Miami-Dade", "Hillsborough", "Indian River", "Polk",
"Brevard", "Orange", "Waukesha", "Lee", "Polk", "Orange", "Seminole",
"Palm Beach", "Lee", "Miami-Dade", "Lee", "Miami-Dade", "Marion",
"Citrus", "Miami-Dade", "Hillsborough", "Polk", "Miami-Dade",
"Pinellas", "St. Lucie", "Polk", "Volusia", "Palm Beach", "Lee",
"Gadsden", "Flagler", "Alachua", "Hernando", "St. Lucie", "Polk",
"Polk", "Pinellas", "Flagler", "Manatee", "Hillsborough", "Polk",
"Charlotte", "Pinellas", "Brevard", "Pinellas", "Broward", "Escambia",
"Citrus", "Palm Beach", "Brevard", "Pasco", "Seminole", "Seminole",
"Miami-Dade", "Miami-Dade", "Indian River", "St. Lucie", "Sumter",
"Broward", "Seminole", "Charlotte", "Lee", "Broward", "Hillsborough",
"Manatee", "Orange", "Hernando", "Lee", "Miami-Dade", "Seminole",
"Orange", NA, "Broward", "Orange", "Manatee", "Orange", "Broward",
"Palm Beach", "Harnett", "Miami-Dade", "Brevard", "Bradford",
"Brevard", "Seminole", NA, "Broward", "Durham", "Santa Rosa",
"Clay", "Grant", "Citrus", "Rutherford", "Wilson", "Polk", "Pinellas",
"Hillsborough", "Flagler", "Miami-Dade", "Hillsborough", "Broward",
"Pasco", "Sumter", "Pinellas", "Seminole", "El Paso", "Forsyth",
"Miami-Dade", "Palm Beach", "Citrus", "Pasquotank", "Polk", "Duval",
"Volusia", "Miami-Dade", "Escambia", "Miami-Dade", "St. Johns",
"Miami-Dade", "Pinellas", "Pinellas", "Marion", "Brown", "Miami-Dade",
NA, "Forsyth", "Milwaukee", "Teller", "Seminole", "Guilford",
"Escambia", "Orange", "Stokes", "Cabarrus", "Lee", "Wake", "Palm Beach",
"Mecklenburg", "Bay", "Milwaukee", "Sarasota", "Broward", "Wood",
"Durham", "New Hanover", "Lake", "La Crosse", "Leon", "Orange",
"Eau Claire", "Miami-Dade", "Martin", "Hernando", "Stanly", "Brunswick",
"Brevard", "Citrus", NA, NA, "Pinellas", "Miami-Dade", "Lee",
"Duval", "Sumter", "Palm Beach", "Outagamie", "Davie", "El Paso",
"Pinellas", "Indian River", "Miami-Dade", "Marion", "Lafayette",
"Wake", "Manatee", "Lee", "Wake", "Broward", "Broward", "Duplin",
"Polk", "Miami-Dade", "Pinellas", "Lee", "Broomfield", "Hillsborough",
"McDowell", "Palm Beach", "Guilford", "Seminole", "Hillsborough",
"Hernando", "Onslow", "Jefferson", "Marathon", NA, "Guilford",
"Pasco", "Marion", "Nash", "Hillsborough", "Wake", "Marion",
"Teller", "St. Lucie", "Jefferson", "Sauk", "Broward", "Wilkes",
"Guilford", "Duval", "Miami-Dade", "Orange", "Rio Grande", "Martin",
"Hernando", "Pinellas", "Wake", "Marathon", "Archuleta", "Guilford",
"Duval", "Miami-Dade", "Haywood", "Fond du Lac", "Wilson", "Union",
"New Hanover", "Lafayette", "Miami-Dade", "Langlade", "Pinellas",
"Orange", "Sauk", "Alamance", "Pinellas", "Volusia", NA, "Broward",
"Denver", "Broward", "Jefferson", "Halifax", "Broward", "Sarasota",
"Onslow", "Mecklenburg", "Osceola", "Hillsborough", "Stanly",
"Miami-Dade", "Stokes", "Duval", "Polk", "Denver", "Seminole",
"Orange", "Hillsborough", "Iredell", "Hillsborough", "Milwaukee",
"Adams", "Mecklenburg", "Craven", "Palm Beach", "Arapahoe", "Palm Beach",
"Pinellas", "Brevard", "Alamance", "Levy", "Winnebago", "St. Johns",
"Palm Beach", "Brunswick", "St. Johns", "Iron", "Osceola", "Lenoir",
"Duval", "Dane", "Miami-Dade", "Hillsborough", "Osceola", "Polk",
"Brevard", "Wakulla", "Stanly", "Pinellas", "Lee", "Broward",
"Palm Beach", "Jackson", "Polk", "Orange", "Douglas", "Hernando",
"Martin", "Miami-Dade", "Lee", "Citrus", NA, "Santa Rosa", "Hillsborough",
"Marion", "Pasco", "Palm Beach", "Marion", "Walworth", "Logan",
"Manitowoc", "Clay", "Outagamie", "Seminole", "Hillsborough",
"Flagler", "Sheboygan", "Broward", "Ozaukee", NA, "Broward",
"Walton", "Volusia", "Sarasota", "Carteret", "Denver", "Broward",
"Hernando", "Waukesha", "Anson", "Gadsden", "Ozaukee", "Adams",
"Marion", "Hillsborough", "Marathon", "Union", "Osceola", "Columbus",
"Pasco", "Miami-Dade", "Miami-Dade", "Broward", "Osceola", "St. Lucie",
"Charlotte", "Hillsborough", "Osceola", "Collier", "Jefferson",
"Nash", "Lake", "Johnston", "Mecklenburg", "Volusia", "Boulder",
"Kenosha", "Hillsborough", "Broward", "Mecklenburg", "Durham",
"Lake", "Washington", "Brevard", "El Paso", "Denver", "Jackson",
"Cabarrus", "Miami-Dade", "Buncombe", "Huerfano", "Alachua",
"Johnston", "Outagamie", "Pasco", "Pueblo", "Orange", "Pinellas",
"Union", "Kenosha", "Dane", "Durham", "Union", "Marathon", "Jefferson",
"Palm Beach", "Hillsborough", "Mecklenburg", "Wake", "Pasco",
"Pinellas", "Pender", "Taylor", "Wake", "Waukesha", "Arapahoe",
"Denver", "Boulder", "Palm Beach", "Sarasota", "St. Lucie", "Guilford",
"El Paso", "Arapahoe", "Arapahoe", "Broward", "Orange", "Rock",
"Arapahoe", "Escambia", "Sarasota", "Johnston", "Miami-Dade",
"Surry", "Surry", "La Plata", "Alamance", "Larimer", "Manatee",
"Davidson", "Miami-Dade", "Wake", "Hillsborough", "Jefferson",
"Buncombe", "Alachua", "Kenosha", "Boulder", "Citrus", "Hillsborough",
"Pitt", "Las Animas", "Sheboygan", NA, "Wood", "Broward", NA,
"Orange", "Duval", "Broward", "Jefferson", "Winnebago", "Oneida",
"Randolph", "Durham", "Buncombe", "Lake", "Larimer", "Madison",
"Gaston", "Miami-Dade", "Teller", "Clay", "Pinellas", "Wake",
"St. Croix", "Pueblo", "Surry", "Wake", "Polk", "Jefferson",
"Douglas", "Milwaukee", "Rock", "Wake", "Waukesha", "Clay", "Cleveland",
"Madison", "Buncombe", "Broward", "Jefferson", "Hillsborough",
"Milwaukee", "Putnam", "Volusia", "Brown", "Weld", "Winnebago",
"Leon", "Stokes", "Manatee", "El Paso", "Alachua", "Forsyth",
"Larimer", "Rock", "Bayfield", "Columbia", "El Paso", "Buncombe",
NA, "Lee", "Cleveland", NA, "Union", "El Paso", "Robeson", "Mecklenburg",
"El Paso", "Alamance", "Rock", "Jefferson", "Douglas", "El Paso",
"Waukesha", "Buncombe", "Davidson", "Arapahoe", "Edgecombe",
"Adams", "Vilas", "Hillsborough", "Brevard", "Lafayette", "Lee",
"Rowan", "Indian River", "Dane", "Larimer", NA, "Hillsborough",
"Jefferson", "Durham", "Orange", "El Paso", "Beaufort", "Arapahoe",
"Outagamie", "El Paso", "Douglas", "Johnston", "Orange", "Denver",
"Durham", "Adams", "Broward", "Sarasota", "Broomfield", "Brevard",
"Johnston", "Dane", "Gaston", "Mecklenburg", "Miami-Dade", "Wake",
"Sarasota", "Door", "Mecklenburg", "Palm Beach", "Broomfield",
"Kenosha", "Milwaukee", "Ashe", "Gadsden", "Palm Beach", "Jefferson",
"Johnston", "Pasquotank", "Union", "Durham", "Dare", "Dane",
"Robeson", "Waukesha", "Durham", "Waukesha", "Miami-Dade", "Alachua",
"Rock", "Teller", "El Paso", "Adams", "Pasco", "Rutherford",
"Alachua", "Lee", "Milwaukee", "Clay", "Washington", "Rock",
"Wake", "Polk", "Fond du Lac", "Pender", "Fremont", "Broward",
"Cabarrus", "Denver", "Rock", "Hillsborough", "Broward", "Lincoln",
"Pinellas", "Waushara", "Wake", "Harnett", "Weld", "Osceola",
"Door", "Waukesha", "Harnett", "Orange", "Wake", "Lee", "Weld",
"Seminole", "Dane", "Brown", "Palm Beach", "Milwaukee", "Shawano",
"Douglas", "Dane", "Oneida", "Boulder", "St. Johns", "Brown",
"Pinellas", "Mecklenburg", "Randolph", "Hillsborough", "Orange",
"Cumberland", "Arapahoe", "Cumberland", "Rockingham", "Moore",
"Dane", "Marathon", "Teller", "Door", "Washington", "Duval",
"Guilford", "Ashland", "Brevard", "Granville", NA, "Dane", "New Hanover",
"Wake", "Henderson", "Hillsborough", "Vernon", "Polk", "Green",
"Lincoln", "Milwaukee", "McDowell", "Logan", "Walworth", "Richmond",
"Pinellas", "El Paso", "Wake", "Jefferson", "Johnston", "Wake",
"Douglas", "El Paso", "Rockingham", "Durham", "Palm Beach", "Orange",
"Langlade", "Milwaukee", "Manatee", "Barron", "Surry", "Lee",
"Manatee", "Hernando", "Brown", "Alleghany", "Franklin", "Winnebago",
"Johnston", "Chatham", "Waukesha", "St. Johns", "Wake", "Miami-Dade",
"Jackson", "Buncombe", "Robeson", "Forsyth", "Manitowoc", "Green",
"Waukesha", "Milwaukee", "Dane", "Union", "Dixie", "Mecklenburg",
"Okaloosa", "Brevard", "Mecklenburg", "Jefferson", "Brown", "Guilford",
"Hernando", "Milwaukee", NA, "Lee", "St. Lucie", "Dane", "Davie",
"La Plata", "Hillsborough", "Dane", "Milwaukee", "Pinellas",
"Broward", "Indian River", "Larimer", "Outagamie", "Guilford",
"Orange", "Wake", "Douglas", "Arapahoe", "Mecklenburg", "Waupaca",
"Adams", "Pasquotank", "Duval", "Lee", "Milwaukee", "Collier",
"Hillsborough", "El Paso", "El Paso", "Racine", "Osceola", "Craven",
"Walworth", "Volusia", "Archuleta", "Okaloosa", "Wood", "Denver",
"Wake", "Denver", "Miami-Dade", "Oneida", "Kenosha", "Wilkes",
"Pasco", "El Paso", "Washington", "Currituck", "La Crosse", "Pinellas",
"Milwaukee", "Milwaukee", "Jefferson", "Chippewa", "Yadkin",
"Davidson", "Henderson", "Washington", "Dane", "Arapahoe", "Broward",
"Denver", "New Hanover", "Johnston", "El Paso", "Wake", "Jefferson",
"Milwaukee", "Craven", "Chatham", "El Paso", "Waukesha", NA,
"Arapahoe", "Cleveland", "Wake", "Caswell", "Collier", "Buncombe",
"Iowa", "Ozaukee", "Washington", "Arapahoe", "Mecklenburg", "New Hanover",
"Mecklenburg", "Nash", "Burke", "San Miguel", "Washington", "Milwaukee",
"Randolph", "Jefferson", "Wake", "Durham", "Lake", "Avery", "Dane",
"Mecklenburg", "Adams", NA, "Caswell", "Mesa", "Wake", NA, "Cabarrus",
"Mesa", "Forsyth", "Putnam", "Weld", "Milwaukee", "Union", "Miami-Dade",
"Manitowoc", "Milwaukee", "Chaffee", "Jefferson", "Arapahoe",
"Rowan", "Pinellas", "Ozaukee", "Catawba", "Calumet", "Jefferson",
"Rusk", "Pender", "Adams", "Onslow", "Rock", "Clay", "Grant",
"Forest", "Milwaukee", "Arapahoe", "Mesa", "Catawba", "Marion",
"Milwaukee", "Pueblo", "Alachua", "Iredell", "Moore", "Okaloosa",
"Waukesha", "Cumberland", "Milwaukee", "Orange", "Rock", "Alexander",
"Gadsden", "Boulder", "Lake", "Milwaukee", "Escambia", "Denver",
"Jefferson", "Miami-Dade", "El Paso", "Hoke", "Iredell", "Pinellas",
"Okaloosa", "Manatee", "Madison", "Pitt", "Orange", "Waupaca",
"Arapahoe", "Guilford", "Mecklenburg", "Oneida", "Waukesha",
"Miami-Dade", "Adams", "Lake", "Dane", "Manatee", "Broward",
"Guilford", "Adams", "Wake", "Taylor", "Johnston", "Madison",
"Denver", "Pueblo", "Northampton", "Mecklenburg", "Pinellas",
"Richland", "Arapahoe", "Mecklenburg", "Forsyth", "Duval", "Miami-Dade",
"Buncombe", "Weld", "Ozaukee", "Mecklenburg", "Pinellas", "Volusia",
"Craven", NA, "Gaston", "Citrus", "Dane", "Washington", "New Hanover",
"Franklin", "Guilford", "Gaston", "Palm Beach", NA, "Racine",
"Arapahoe", "Leon", "Brown", "Miami-Dade", "Brown", "Marion",
"Duval", "Rockingham", "Highlands", "Halifax", "Guilford", "Davidson",
"Forsyth", "Hillsborough", "Arapahoe", "Palm Beach", "Onslow",
"Onslow", "Larimer", "Dodge", "Seminole", "Clay", "Cleveland",
"Hernando", "Racine", "Denver", "El Paso", "Marion", "Vilas",
"Waukesha", NA, "Pasco", "El Paso", "Fond du Lac", "Manatee",
"Palm Beach", "Clark", "Milwaukee", "El Paso", "Waupaca", "Weld",
"DeSoto", "Orange", "Orange", "Denver", "Miami-Dade", "Guilford",
"St. Croix", "Archuleta", "Larimer", "Wake", "Wake", "Palm Beach",
"Mecklenburg", "Martin", "Lake", "Flagler", "Elbert", "Rockingham",
"Hillsborough", "Haywood", "Carteret", "Delta", "Catawba", "Brunswick",
"Arapahoe", "Guilford", "La Plata", "Forsyth", "Arapahoe", "Rutherford",
"Milwaukee", "Charlotte", "La Crosse", "Rockingham", "Escambia",
"Dane", "Rowan", "Wake", "Union", "Granville", "Arapahoe", "Alachua",
"Osceola", "Arapahoe", "Douglas", "Leon", "Haywood", "Morgan",
"Ozaukee", "Hillsborough", "Hernando", "Brevard", "Dane", "Sheboygan",
"Dane", "Manitowoc", "Mitchell", "Guilford", "Wake", "Cherokee",
"Hillsborough", "Palm Beach", "Milwaukee", "Portage", "El Paso",
"Pasquotank", "Martin", "Denver", "La Plata", NA, "Harnett",
"Outagamie", "Johnston", "Racine", "Polk", "Kenosha", "Arapahoe",
"Cabarrus", "Fond du Lac", "Sauk", "Dane", "Alleghany", "New Hanover",
"Larimer", "Sarasota", "Huerfano", "Dane", "Brevard", "Alamance",
"Arapahoe", "Orange", "Macon", "Weld", "Duval", "Saguache", "Columbia",
"Forsyth", "Davidson", "Conejos", "Boulder", "Winnebago", "Arapahoe",
"Volusia", "El Paso", "Richmond", "Weld", "Montezuma", "Polk",
"Lee", "Stanly", "Kenosha", NA, "Johnston", "Brown", "Pitt",
"Milwaukee", "Duplin", "Currituck", "Onslow", "Dane", "Cherokee",
"Mecklenburg", "Weld", "Pueblo", "St. Croix", "Douglas", "Watauga",
"Guilford", "Arapahoe", "Lincoln", "Leon", "Barron", "Brown",
"Outagamie", "Guilford", "El Paso", "Caldwell", "Okaloosa", "El Paso",
"Manitowoc", "Teller", "Adams", "Waukesha", "Dane", "Rock", "Rock",
"New Hanover", "Guilford", "Milwaukee", "Arapahoe", "Larimer",
"Arapahoe", "Wake", "Arapahoe", "Jefferson", NA, "Alamance",
"Chatham", "La Crosse", "Logan", "Racine", "Dane", "St. Lucie",
"Wake", "Durham", "Wake", "Rockingham", NA, NA, "Currituck",
"Guilford", "Wake", "Mecklenburg", "Durham", "Racine", "New Hanover",
"Cabarrus", "Barron", "Citrus", "Douglas", "Dane", "Wake", "Walworth",
"Milwaukee", "Portage", "Polk", "Logan", "Jefferson", "Milwaukee",
"Wake", "Mecklenburg", "Pitkin", "Boulder", "Nash", "Racine",
"Larimer", "Wake", "Wake", "Marathon", "Gaston", "Mecklenburg",
"Jefferson", "Pasco", "Adams", "Wake", "Milwaukee", "Craven",
"Pitt", "Broward", "Arapahoe", "Craven", NA, "Seminole", "Sheboygan",
"Larimer", "Brevard", NA, "Guilford", "Pinellas", "Sarasota",
"Broward", "Rock", "Miami-Dade", "Douglas", NA, "Douglas", "Larimer",
"Hillsborough", "Lee", "Rock", "Sheboygan", "Nassau", "Marquette",
"Volusia", "Dane", NA, "Duval", "Sheboygan", "Milwaukee", "Milwaukee",
"Wake", "Marathon", "Lincoln", "Guilford", "Milwaukee", "Rock",
"El Paso", "Cleveland", "Arapahoe", "Denver", "Waukesha", "Milwaukee",
"Milwaukee", "El Paso", "Miami-Dade", "Jefferson", "Outagamie",
"St. Johns", "Denver", "Nash", "Duval", "Shawano", "Pueblo",
"Rock", "Forsyth", "Guilford", "Wake", "Jefferson", "Sheboygan",
"Brunswick", "Rockingham", "Arapahoe", "Denver", "Clark", "Denver",
"Cleveland", "Arapahoe", "Columbia", "Macon", "Racine", "El Paso",
"Weld", "Iredell", "Douglas", "Union", "Larimer", "Jefferson",
"Citrus", "Dane", "Arapahoe", "Denver", "Douglas", "El Paso",
"Weld", "Denver", "Adams", "Broomfield", "Boulder", "Polk", "Dane",
"Durham", "Arapahoe", "El Paso", "Arapahoe", "Larimer", "Denver",
"Jefferson", "Durham", "Jefferson", "Mesa", "Brown", "Brunswick",
"Waupaca", "Winnebago", "Mesa", "Mecklenburg", "El Paso", "Wake",
"Denver", "Orange", "El Paso", "Garfield", "Milwaukee", "Waukesha",
"Mecklenburg", "Eau Claire", "Transylvania", "Mecklenburg", "Guilford",
"Surry", "Forsyth", "Dane", "Kenosha", "Henderson", "Buncombe",
"Durham", "El Paso", "Dane", "Guilford", "Moore", "Forsyth",
"Milwaukee", "Jefferson", NA, "Orange", "Arapahoe", "Robeson",
"Mecklenburg", "La Plata", "Boulder", "Douglas", NA, "Stokes",
"Jefferson", "Mesa", "Arapahoe", "Perquimans", "Boulder", NA,
"Milwaukee", "Milwaukee", "Dodge", "Montrose", "Caldwell", "Arapahoe",
"Ashe", "Winnebago", "Brown", "Arapahoe", "Durham", "Forsyth",
"Jackson", "Macon", "Rowan", "Wake", "Outagamie", "Chatham",
"Mecklenburg", "Wayne", "Denver", "Mesa", "McDowell", "Beaufort",
"Larimer", "Adams", "Brunswick", "Boulder", "Forsyth", "Jefferson",
"Rockingham", "Rock", "Mecklenburg", "Guilford", "Wake", "Caldwell",
"Waukesha", "Outagamie", "Durham", "Orange", "Robeson", "Davidson",
"Lenoir", "Douglas", "Fond du Lac", "Jefferson", "Guilford",
"Boulder", "Milwaukee", "Dane", "Burke", "Jefferson", "Barron",
"Burnett", "El Paso", "Dane", "El Paso", "Guilford", "St. Croix",
"Guilford", "Waukesha", "Arapahoe", "Adams", "Buncombe", "Forsyth",
"Arapahoe", "Arapahoe", "Wake", "Pitt", "Mesa", "Douglas", "Clark",
"Milwaukee", "El Paso", "Douglas", "El Paso", "Buncombe", "Orange",
"Davidson", "Burke", NA, "Alexander", "Orange", "St. Croix",
"Winnebago", "Brunswick", "Lenoir", "Racine", "Harnett", "Milwaukee",
"Union", "Davidson", "Mecklenburg", "Dane", "Catawba", "Denver",
"Wake", "El Paso", "Durham", "Durham", "Racine", "Wake", "Waukesha",
"Davidson", "Rock", "Cabarrus", "Wake", "Racine", "El Paso",
"Cabarrus", "Randolph", "Hillsborough", "El Paso", "Winnebago",
"Gaston", "Milwaukee", "Montrose", "Buncombe", "El Paso", "Burnett",
"Mecklenburg", "Jefferson", "Cumberland", "Iowa", "Columbus",
"El Paso", "Dane", "Mecklenburg", "Guilford", "Adams", "Elbert",
"Milwaukee", "Nash", "St. Croix", "Douglas", "Buncombe", "Randolph",
"Henderson", "Brunswick", "Duval", NA, "Wake", "Morgan", "New Hanover",
"Guilford", "Rowan", "Dane", "Wake", "Dane", "Douglas", "El Paso",
"Brunswick", "El Paso", "Brown", "Brown", "Richland", "Rowan",
"Vernon", "Larimer", "Wake", "Person", "Orange", "Park", "Walworth",
"Haywood", "Cherokee", "Waupaca", "Arapahoe", "Milwaukee", "Alamance",
"Pueblo", "Guilford", "Buncombe", "Denver", "Douglas", "Portage",
"Durham", "Johnston", "Wake", "Durham", "Grant", "Henderson",
"Brown", "La Crosse", "Cabarrus", "Archuleta", "Winnebago", "Green Lake",
"El Paso", "Columbia", "Boulder", "Forsyth", "El Paso", "Randolph",
"Winnebago", "Marathon", "Orange", NA, "Dane", "El Paso", "Iredell",
"Grant", "Adams", "Washington", "El Paso", "Sheboygan", "Catawba",
"Brown", NA, "Wake", "Craven", "Durham", "Mecklenburg", "Union",
"Adams", "Cabarrus", "Milwaukee", "Mecklenburg", "Dane", "Buncombe",
"El Paso", "Douglas", "Cherokee", "El Paso", "Jefferson", "Mesa",
"Racine", "Greene", "Dare", "Larimer", "Carteret", "Forsyth",
"Manitowoc", "Onslow", "Denver", "Transylvania", "Pender", "Mesa",
"El Paso", "Cabarrus", "Denver", "New Hanover", "Buncombe", "Larimer",
"Wake", "Mecklenburg", "Racine", "El Paso", "Arapahoe", "Duval",
"Douglas", "Watauga", "El Paso", "Walworth", "Kenosha", "Pitt",
"La Plata", "St. Croix", "Haywood", "Weld", "Larimer", "Gaston",
"Mecklenburg", "Garfield", "Washington", "Buncombe", "Wake",
"Douglas", "Milwaukee", "Forsyth", "Mecklenburg", "Lee", "Burke",
"Orange", "Macon", "Door", "Johnston", "Mesa", "Gaston", "Milwaukee",
"Henderson", "Milwaukee", "Arapahoe", "Chatham", "Denver", "Boulder",
NA, "Pasquotank", "Larimer", NA, "Brown", "Milwaukee", "Dane",
"Palm Beach", "Oneida", NA, "Henderson", "Outagamie", "Vilas",
"Delta", "Guilford", "Montezuma", NA, "Waukesha", "Jefferson",
NA, "Durham", "Rowan", "Mecklenburg", "Dane", NA, "Pitt", "Larimer",
"Dane", "Wake", NA, "Moore", "El Paso", "Milwaukee", "Brevard",
"Jefferson", "Adams", NA, "Wake", "Forsyth", "Dane", "Lenoir",
"La Crosse", "Milwaukee", "Wake", "Wake", "Person", "Barron",
"Catawba", "Bladen", "Moore", "Dane", "El Paso", "Cumberland",
"Brunswick", "Wake", "Larimer", "Mecklenburg", "Mineral", "Larimer",
"Larimer", "Milwaukee", "Lincoln", "Duval", "Racine", NA, "Jefferson",
"Denver", "Forsyth", "Wake", "Wake", "Wake", "Catawba", "El Paso",
"Eau Claire", "Rock", "Teller", "Adams", "Kenosha", "Chatham",
"Henderson", "Huerfano", "Pierce", "Wake", "La Plata", "Arapahoe",
"Denver", "Green", "Door", "Person", "Wake", "Racine", "Hoke",
"Adams", "Winnebago", "Marinette", "Onslow", "Moore", "Moore",
"Richmond", "Denver", "Wake", "Guilford", "Mesa", "Pueblo", "Wilkes",
"New Hanover", "Wayne", "Winnebago", "Delta", NA, "Gaston", "Buffalo",
"Larimer", "Durham", "Pueblo", "Alamance", "Mecklenburg", "Fond du Lac",
NA, "Buncombe", NA, "Teller", "Guilford", "Alamance", NA, "Mecklenburg",
"Onslow", "Buncombe", "Jefferson", "Winnebago", "Dodge", "Jefferson",
"Outagamie", "Guilford", "Wake", "Jefferson", "Forsyth", "Chaffee",
"Granville", "Clark", "Larimer", "Mecklenburg", "Adams", "Arapahoe",
"El Paso", "Caldwell", "Adams", "Wake", "Mecklenburg", "Henderson",
NA, "Iredell", "Mecklenburg", "Denver", NA, "Columbia", "Adams",
"Pasco", "McDowell", "Rock", "Burke", "Polk", "Cherokee", "Douglas",
"Denver", "Larimer", "Arapahoe", "Jefferson", "Washington", "Jefferson",
"Durham", "Carteret", "Dane", "Douglas", "Douglas", "Iredell",
"Douglas", "La Plata", "New Hanover", "Brown", "La Crosse", "Arapahoe",
"Cumberland", "La Plata", "Catawba", "Garfield", "Clay", "Jefferson",
"Buncombe", "Sawyer", "Jefferson", "Dane", "Brunswick", "Polk",
"Mecklenburg", "Boulder", "El Paso", "Durham", "Teller", "El Paso",
"Arapahoe", "Larimer", "Stanly", "Arapahoe", "Guilford", "Dane",
"Osceola", "Alleghany", NA, NA, "Boulder", "Milwaukee", "Mecklenburg",
"Mecklenburg", "Forsyth", "Mecklenburg", "Waukesha", "Lincoln",
"Sampson", "Collier", "Rock", "Cabarrus", "Transylvania", "Jefferson",
"Mecklenburg", NA, "El Paso", "Rockingham", "Lenoir", "Jefferson",
"Dane", "Arapahoe", "Johnston", "Mecklenburg", "Racine", "Pueblo",
NA, "Milwaukee", "Rock", "Dane", "Denver", "Cumberland", NA,
"Union", "Guilford", "Larimer", "Summit", "Durham", "Green",
"El Paso", "Jefferson", "Larimer", "Wake", "El Paso", "Durham",
"El Paso", NA, "Iredell", "Mecklenburg", "Milwaukee", "Forsyth",
"Brunswick", "Rutherford", "Wake", "Waukesha", "Pinellas", "Kenosha",
"Pueblo", "Moore", "Mecklenburg", "Flagler", "Nash", "Durham",
"Guilford", "Guilford", "Guilford", "Forsyth", "El Paso", "Adams",
"Teller", "Burke", "Pueblo", "Buncombe", "Kenosha", "Weld", "Orange",
"Pender", "Rowan", "Polk", "Randolph", "Douglas", "Winnebago",
"Milwaukee", "Dane", "Waukesha", "El Paso", "Milwaukee", "Arapahoe",
"Union", "Arapahoe", "Forsyth", "Jefferson", "Cabarrus", "Douglas",
"Eau Claire", "Fond du Lac", "Adams", "Person", "Surry", "Wake",
"Dodge", "Brunswick", "Volusia", "Florence", "Adams", "Rowan",
"Catawba", "Jefferson", "Adams", "Onslow", "Burke", "Durham",
"Waukesha", "Denver", "Guilford", "Pitt", "Milwaukee", "Arapahoe",
"Cabarrus", "Jones", "Wake", "Weld", "Denver", "Outagamie", "Currituck",
"Monroe", "Sheboygan", "Lenoir", "Mesa", "Cabarrus", "Leon",
"Denver", "Wake", "El Paso", "Douglas", "Winnebago", "Denver",
"Transylvania", "Larimer", "Fremont", "Cabarrus", "Boulder",
"Durham", "Milwaukee", "Durham", "Moore", "Jefferson", "Weld",
"Dodge", "Davidson", "Henderson", "Marion", "Union", NA, "Franklin",
"Dane", "Guilford", "Transylvania", "Mesa", "El Paso", "Lee",
"Lee", "Dane", "Green", "Milwaukee", "Denver", "New Hanover",
"Guilford", "Brown", "Chippewa", "Adams", "Portage", "Dodge",
"Transylvania", "El Paso", "Gaston", "Archuleta", "Camden", "Calumet",
"Onslow", "Outagamie", "Wayne", "Vilas", "Guilford", "Wood",
"Mecklenburg", "Waukesha", "Weld", "Delta", "Wake", "Craven",
"Winnebago", "Milwaukee", "Summit", "Mecklenburg", "Boulder",
"Hernando", "Jefferson", "Clark", "Wake", "Larimer", "Jones",
"Mecklenburg", "Arapahoe", "Walworth", "Washington", "Jefferson",
"Brunswick", "Bertie", "Cumberland", "Mesa", "Milwaukee", "Pueblo",
"Mecklenburg", "Huerfano", "Kenosha", "St. Croix", "Dane", "Pueblo",
"Douglas", "Jefferson", "Trempealeau", "Weld", "Logan", "Brown",
"Boulder", "Pitt", "Milwaukee", "Fremont", "Wake", "Oconto",
"Douglas", "Forsyth", "Kenosha", "Miami-Dade", "Arapahoe", NA,
"Watauga", "Kenosha", "Arapahoe", "Mesa", "Adams", "Denver",
"Dane", "Adams", "Arapahoe", "Boulder", "Harnett", "Wake", "Douglas",
"Marathon", NA, "Denver", "Pueblo", "Jefferson", "Pueblo", "Durham",
"El Paso", NA, "McDowell", "Door", "Lincoln", "Polk", "Catawba",
"Adams", "Arapahoe", "Moore", "Sarasota", "Forsyth", "Brown",
"Barron", "Okaloosa", "Dane", "Moore", "Miami-Dade", "Arapahoe",
"Kenosha", "Lake", "Marathon", "Cabarrus", "Martin", "Milwaukee",
"Grant", NA, "Forsyth", NA, "Chatham", "Carteret", "Wake", "Forsyth",
"Wake", "Denver", NA, "Montrose", "Racine", "Sheboygan", NA,
"Milwaukee", "Guilford", "Arapahoe", "Ozaukee", "Franklin", "Eagle",
NA, "Denver", "Larimer", "Caldwell", "Milwaukee", "Union", "Jackson",
"Jefferson", "Jefferson", "Duval", "Davidson", "Randolph", "Gates",
"Taylor", "Dane", "Sheboygan", "Arapahoe", "Arapahoe", "Wake",
"Transylvania", "Dunn", "Broward", NA, "Sawyer", "Arapahoe",
"Carteret", "Orange", "Ozaukee", "Kenosha", "Arapahoe", "Vilas",
"Milwaukee", "Henderson", "Lincoln", "Weld", "Martin", "Yancey",
"Onslow", "Lincoln", "Wake", "Wake", "Milwaukee", "Milwaukee",
"Burnett", "Lincoln", "St. Croix", "Milwaukee", "Carteret", "Boulder",
"Cumberland", "Jefferson", "Morgan", "Chippewa", "Montrose",
NA, "Wake", "Brunswick", "Milwaukee", "Arapahoe", "Union", "Waupaca",
"Davidson", "Robeson", "Sampson", "Denver", "Larimer", "Outagamie",
"Arapahoe", "Cherokee", "Dane", "Denver", "Arapahoe", NA, "Larimer",
"Orange", "Jefferson", "Pueblo", "Dane", "Cumberland", "Lincoln",
"Waukesha", "Racine", "Forsyth", "Wood", "Brown", "Wake", "Arapahoe",
NA, NA, "Volusia", "Adams", "Forsyth", "Macon", "Wake", "Denver",
"Door", "Mecklenburg", "Larimer", "Lincoln", "Marathon", "Pinellas",
"Elbert", "Buncombe", "Brown", "Adams", "Washington", "Martin",
"El Paso", "McDowell", "Warren", "Mecklenburg", "Seminole", "Forsyth",
"Haywood", "Marathon", "Jefferson", "Pasco", "New Hanover", "Summit",
"Buncombe", "Onslow", "Brunswick", "Brown", "Buncombe", "Arapahoe",
"Milwaukee", "Guilford", "Cabarrus", "Henderson", "Fremont",
"Yancey", NA, "Arapahoe", "Chatham", NA, "Waukesha", "Davie",
"Wake", "Mecklenburg", "Boulder", "Durham", "Wake", "Jefferson",
"Craven", "Osceola", "Craven", "Eau Claire", "New Hanover", "El Paso",
"Carteret", "Wayne", "Denver", "Larimer", "Scotland", "Duval",
"Crowley", "Washburn", "New Hanover", "Denver", "Weld", "Walworth",
"Pasco", "Jefferson", "Wake", "Forest", NA, "Union", "Mecklenburg",
"Lenoir", "Chippewa", "Haywood", NA, "Arapahoe", "Milwaukee",
"El Paso", "Forsyth", "Bertie", "Cumberland", "Cleveland", "Brunswick",
"Brunswick", "Arapahoe", "Cabarrus", "Wayne", "Milwaukee", "Jefferson",
"Dane", "Davidson", "Denver", "Ouray", "Carteret", "El Paso",
"Denver", "Walworth", "Larimer", "Montrose", "Boulder", "Denver",
"Jefferson", "El Paso", "Douglas", "Larimer", "Eau Claire", "Cumberland",
"Wake", "Cumberland", "Jefferson", "Arapahoe", "Adams", "Brown",
"Pitkin", NA, "Mecklenburg", "Burke", "Wood", "Mecklenburg",
NA, "Custer", "Waupaca", "Jefferson", "Ozaukee", "Burke", "Dane",
"Perquimans", "Forsyth", "Jefferson", "Rockingham", "Pueblo",
"Winnebago", "Adams", "Rock", "Nash", "Randolph", "El Paso",
"Forsyth", "Elbert", "Union", "Wake", "Jefferson", "Milwaukee",
"Fond du Lac", "Adams", "Adams", "Iron", "Rowan", "Wake", "Mecklenburg",
"Delta", "Bertie", "Denver", "Pueblo", "Denver", "Santa Rosa",
"Forsyth", NA, "McDowell", "Douglas", "Arapahoe", NA, "Milwaukee",
"Union", "Wake", "Brown", "Denver", "Adams", "Calumet", "Forsyth",
"Ozaukee", "Chippewa", "Union", NA, "Wake", "Barron", "New Hanover",
"Douglas", "Douglas", "Crawford", "El Paso", "Sarasota", "Milwaukee",
"Bayfield", "Orange", "Forsyth", "Mecklenburg", "Burke", "Mecklenburg",
"Burke", "Adams", "El Paso", "Douglas", "Johnston", "Arapahoe",
"Guilford", "Dane", "Douglas", "Ozaukee", "Lake", "Larimer",
"Wake", "Caldwell", "Wilson", "Dane", "Mesa", "Custer", "Wayne",
"Walworth", "Jefferson", "Arapahoe", "Racine", "Douglas", "Denver",
"El Paso", "Swain", "Durham", "Moore", "Wake", "Pueblo", "Wake",
NA, "Denver", "Wake", NA, "Madison", "Volusia", "Wayne", "Dane",
"Denver", "Milwaukee", "Haywood", "Manitowoc", "Yancey", "Monroe",
NA, "Oconto", "Adams", "Franklin", "Boulder", "Grant", "Chowan",
"Morgan", "Buncombe", "Dane", NA, "Orange", "Chippewa", "Randolph",
"Rutherford", "Palm Beach", "Rowan", "Arapahoe", "Milwaukee",
"Guilford", "Douglas", "Boulder", "Dane", "Davie", "Sheboygan",
"Wake", "Cabarrus", "New Hanover", "Broward", "Arapahoe", "Adams",
"Larimer", "Outagamie", "Douglas", "Jefferson", "Arapahoe", "Cherokee",
"Boulder", "Davidson", "Pueblo", "Manitowoc", "Harnett", "Guilford",
"Arapahoe", "Boulder", "Durham", "Denver", "Craven", "Washington",
"Rock", "Columbia", "Guilford", "Delta", "Guilford", "Arapahoe",
"Racine", "Mecklenburg", "Jefferson", "Florence", "Rio Blanco",
"Boulder", "Brown", "Catawba", "Henderson", "Ozaukee", "El Paso",
"Adams", "Arapahoe", "Wake", "Rock", "Brunswick", "Denver", "Beaufort",
"Milwaukee", "Elbert", "Craven", "Wake", "Union", "Mecklenburg",
"Waukesha", "Jefferson", "Forsyth", "Richmond", "Adams", "Wake",
"Denver", "Nassau", "Douglas", "Outagamie", "Douglas", "Duplin",
"Sheboygan", "Arapahoe", "Garfield", "Forsyth", "Henderson",
"Wake", "Denver", "Wake", "El Paso", "Prowers", "Boulder", "Madison",
"Larimer", "Portage", "Weld", "Rockingham", "El Paso", "Guilford",
"Wake", "Harnett", "Kenosha", "El Paso", "Crawford", "Elbert",
"Jefferson", "Pueblo", "Waukesha", "Denver", "Jefferson", "Larimer",
"Pierce", "Burnett", "Guilford", "Edgecombe", "El Paso", "Milwaukee",
"Denver", "Mesa", NA, "Randolph", "Madison", "Forsyth", "Weld",
"Denver", "Denver", "Hoke", "Polk", "Pierce", "El Paso", "Durham",
"Hillsborough", "Kenosha", "Adams", "Marathon", "Wake", "El Paso",
NA, "Mecklenburg", "Waukesha", "Alamance", NA, "Larimer", "Boulder",
"Nash", "Lee", "El Paso", "Polk", "Cabarrus", "Dane", "Waukesha",
"Adams", "Columbia", "Teller", "Denver", "Moffat", "Gaston",
"Larimer", "Nassau", "Racine", "Waukesha", "Sarasota", "Iredell",
"Durham", "Denver", "Forsyth", "Cumberland", "Onslow", "Mecklenburg",
"Brown", "Kenosha", "Iredell", "Milwaukee", "Guilford", "Las Animas",
"El Paso", "Marathon", "Mesa", "Wayne", "Dane", "Brown", "New Hanover",
"New Hanover", "Fremont", "Moore", "Forsyth", "Guilford", "Brown",
"Cumberland", "Durham", "Harnett", "Forsyth", "Winnebago", "Arapahoe",
"Winnebago", "Denver", "Chemung NY", "Clay", "Jefferson", "Barron",
"Henderson", "Wake", "Burke", "Arapahoe", "Pitt", "Orange", "Outagamie",
"Chatham", "Jefferson", "Davie", "Columbia", "Racine", "Polk",
"New Hanover", "Davie", "Dunn", "Broomfield", "Arapahoe", "Davidson",
"Cabarrus", "Cumberland", "Leon", "Waukesha", "Outagamie", "Racine",
"Wake", "Buncombe", "Pueblo", "Guilford", "Jefferson", "Caldwell",
"Sheboygan", "Kenosha", "Fond du Lac", "Brunswick", "Rockingham",
"Douglas", "Denver", "Ozaukee", "Brunswick", "Pierce", "Buncombe",
"Kenosha", "Mecklenburg", "Wake", "Columbia", "Okaloosa", "El Paso",
"El Paso", "Boulder", "Broward", "Forsyth", "Alamance", "Clark",
"Denver", "Wake", "Broward", "Oneida", "Guilford", "El Paso",
"Dane", "Sheboygan", "Gaston", "Brown", "Winnebago", "Miami-Dade",
"Wake", "Wake", "El Paso", "Forsyth", "Larimer", "Mecklenburg",
"St. Lucie", "Iredell", "Sawyer", "Palm Beach", "Wilkes", "Denver",
"Swain", "Guilford", "Wake", "Durham", "Racine", "Washington",
"Mecklenburg", "Winnebago", "Wake", "Adams", "Chatham", "Eau Claire",
"Polk", "Union", "Milwaukee", "Mesa", "Waukesha", "Iredell",
"Grant", "Pitt", "Oconto", "Outagamie", "Jefferson", "Manitowoc",
"Denver", "Summit", "Dane", NA, "Marathon", "Douglas", "Wake",
"Iredell", "Randolph", "Brevard", "Wood", "El Paso", "Lafayette",
"Douglas", "Adams", "Sauk", "El Paso", "Forsyth", "Marathon",
"Buncombe", "Rockingham", "Currituck", "Wake", NA, "Portage",
"Cabarrus", "Taylor", "Brunswick", "Rock", "Arapahoe", "Dane",
"Mecklenburg", "Arapahoe", "Arapahoe", "Waukesha", "Waukesha",
"Mesa", "Durham", "St. Johns", "Broomfield", "Miami-Dade", "Wilson",
"Denver", "Mecklenburg", "Racine", "Alachua", "Dane", "Mecklenburg",
"La Crosse", "Mecklenburg", "Gaston", "Lee", "Milwaukee", "Yancey",
NA, "Miami-Dade", "Guilford", "Leon", "Wake", "Denver", "Forsyth",
"Waukesha", NA, "Calumet", "Union", "Cabarrus", "Buncombe", "Dunn",
"Granville", NA, "Carteret", "Adams", "Chaffee", "Gaston", "Orange",
"Teller", "Wood", "Cabarrus", "Nash", "Vernon", "Milwaukee",
"Onslow", "Pender", NA, "Washington", "Marathon", "Wilkes", "Denver",
"El Paso", "Guilford", "Forsyth", "Jefferson", "Guilford", NA,
"Wake", "Dane", NA, "Boulder", "Conejos", "Boulder", "Burke",
"Milwaukee", "Macon", "Adams", "Rock", NA, "Wake", "Durham",
"Denver", "Larimer", "Weld", "Milwaukee", "El Paso", "Cumberland",
NA, "Beaufort", "Wake", "Arapahoe", "Wayne", "Forsyth", "Columbia",
"Watauga", "Burnett", "Arapahoe", "Surry", "Cumberland", "Seminole",
"El Paso", "Clay", "Mecklenburg", "Shawano", "Pasco", "Rock",
"Buncombe", "Wilkes", "El Paso", "Walworth", "Arapahoe", "Jefferson",
"Martin", "Boulder", "Wake", "Weld", "Dodge", "Denver", "Lee",
"Price", "Dunn", "Douglas", "Montrose", "Wake", "Dane", "Forsyth",
"Weld", "Mecklenburg", "Pueblo", "Dodge", "New Hanover", NA,
"Outagamie", "Otero", "Douglas", "Shawano", "El Paso", "Cabarrus",
"Milwaukee", "Onslow", "Pitt", "Waukesha", "Mecklenburg", "Denver",
"Arapahoe", "Jefferson", "Pitkin", "Buncombe", NA, "Cabarrus",
"Garfield", "New Hanover", "Perquimans", "Wake", "Dane", "Larimer",
"Brown", "Lee", "Brown", "Larimer", "Pitt", "Denver", "Durham",
"Denver", NA, "Douglas", "Jefferson", "Arapahoe", "Wake", "Union",
"Iredell", "Adams", "Montrose", "Wake", "Eau Claire", "La Crosse",
"Pasquotank", "Moore", "Orange", "Mesa", "Jefferson", "Dane",
"Columbia", "Mecklenburg", "Johnston", "Wake", "Jefferson", "Haywood",
"Douglas", "Barron", "Polk", "Stokes", "Racine", "Manitowoc",
"Wake", "St. Johns", "Sauk", "Grant", NA, "Broomfield", "Onslow",
"Denver", "Washington", "Arapahoe", "Jefferson", "Jefferson",
NA, "Milwaukee", "Cleveland", "Summit", "New Hanover", "Orange",
"Arapahoe", NA, "Miami-Dade", "Fremont", "Wilson", "Guilford",
"Guilford", "Gilpin", "Jefferson", "Weld", "Dane", "Wake", "Boulder",
"Mecklenburg", "Lincoln", "Jefferson", "Gunnison", "Wilkes",
"Wake", "Kenosha", "Boulder", "Gaston", "Kenosha", "Denver",
"Boulder", NA, "Elbert", "Wake", "Dunn", "Jefferson", "Orange",
"Wake", "Broward", "Wake", "Milwaukee", "Denver", "Denver", "Lake",
"Ozaukee", "Alamance", "Dane", "Waupaca", "Montezuma", "Wake",
"Denver", "Mesa", "Jefferson", "Pierce", "Waukesha", "Jefferson",
"Arapahoe", "Adams", "Randolph", "Jefferson", "Richmond", "El Paso",
"Brown", "Wake", "Mecklenburg", "Gunnison", "Adams", "Wake",
"Jefferson", "Brown", "Arapahoe", "Waukesha", "Waukesha", "Jefferson",
"Rowan", "Cumberland", "Dane", "Denver", "El Paso", "Brown",
"El Paso", "Milwaukee", "Palm Beach", "Jefferson", "Milwaukee",
"El Paso", "Broomfield", "Cumberland", NA, "Pender", "Mecklenburg",
"El Paso", "Rowan", NA, "Boulder", "Arapahoe", "Ozaukee", "Forsyth",
"Miami-Dade", NA, "Waukesha", "Milwaukee", "Douglas", "Cumberland",
"Milwaukee", "Waupaca", "Milwaukee", "Boulder", "Catawba", "La Crosse",
"Durham", "Dane", "Florence", "Larimer", "New Hanover", "Wake",
"Montezuma", "Fond du Lac", "Outagamie", "Arapahoe", "Denver",
"Arapahoe", "Door", "Wake", "Forsyth", "Pitt", "Douglas", "Marathon",
"Broward", "Mecklenburg", "Jefferson", "Denver", "Hoke", "El Paso",
"Racine", "Walworth", "Oneida", "Winnebago", "Davidson", "Outagamie",
"Bent", "Guilford", "Dane", "Douglas", "Miami-Dade", "Winnebago",
"Nash", "Adams", "Denver", "Durham", "Vilas", "Columbia", "Milwaukee",
"Stanly", "Sheboygan", "Jefferson", "Racine", "Cleveland", "Jefferson",
"Buncombe", "Cumberland", "Dunn", "Arapahoe", "Iredell", "Racine",
"El Paso", "Dane", "Rowan", "Douglas", "Adams", "Burnett", NA,
"Larimer", "El Paso", "Mecklenburg", "Arapahoe", "Denver", "Adams",
"Watauga", NA, "Jefferson", "Arapahoe", "Boulder", "Denver",
"Sauk", "Dane", "Mesa", "Kewaunee", "Seminole", "Vernon", "Richland",
"Rock", "Douglas", "Arapahoe", "El Paso", "Gaston", "Rock", "Winnebago",
"Durham", "El Paso", "Denver", "Fond du Lac", "Juneau", "Arapahoe",
"Arapahoe", "Tyrrell", "Montezuma", "Denver", "Wake", "Lincoln",
NA, "Arapahoe", "Ozaukee", NA, "Waukesha", "New Hanover", "Jones",
"El Paso", "Ozaukee", "El Paso", "Hernando", "Calumet", "Mecklenburg",
"Douglas", "Weld", "Davidson", "Milwaukee", "Nash", "Halifax",
"Broward", "Union", "Dane", "Denver", "Arapahoe", "Person", "Orange",
"Mecklenburg", "Okaloosa", "Fond du Lac", "Chatham", "Arapahoe",
"Jefferson", "Henderson", "Pueblo", "Gaston", "Milwaukee", "Macon",
"Catawba", "Mecklenburg", "Waukesha", "Citrus", "Mecklenburg",
"Mecklenburg", "Broomfield", "Orange", "Guilford", "Citrus",
"Montrose", "Broward", "Ozaukee", "Waukesha", "Sarasota", "Teller",
"El Paso", "Wayne", "La Plata", "Garfield", "Onslow", "Gaston",
"El Paso", "Denver", "Brunswick", "Rowan", "Washington", "Arapahoe",
"Brevard", "Polk", "Shawano", "Craven", "El Paso", "Palm Beach",
"Wake", "Pasco", "Eau Claire", "Milwaukee", "Douglas", "Wake",
"Routt", "Guilford", "Montrose", "Boulder", "El Paso", "Lake",
"Granville", "Waupaca", "Kewaunee", "Fond du Lac", "Price", "Guilford",
"Denver", NA, NA, "Wake", "Waukesha", "Cumberland", "Summit",
"Escambia", "Jefferson", "Halifax", "Ozaukee", "Iredell", "Henderson",
"Sheboygan", "Arapahoe", "Dane", "Clear Creek", "Milwaukee",
"Marion", "Wake", "Columbus", "Carteret", NA, "Denver", "Denver",
"Catawba", "Mecklenburg", NA, "El Paso", "Brevard", "Wake", "Adams",
"Pasco", "Jefferson", "Mecklenburg", "Dane", "El Paso", "El Paso",
"Denver", "Granville", "Brown", "El Paso", "Miami-Dade", "Jefferson",
"Eau Claire", "Sampson", "Kenosha", "Jefferson", "Jefferson",
"Mesa", "Larimer", "Arapahoe", "Adams", "Guilford", "Chaffee",
"Jefferson", "Adams", "Wake", "Boulder", "Pueblo", "Stanly",
"Palm Beach", "Jefferson", "Jefferson", "Montrose", NA, "Milwaukee",
"Douglas", NA, "Gaston", "Arapahoe", "Rio Grande", "Onslow",
"Dane", "Arapahoe", "Okaloosa", "Milwaukee", "Denver", "Pender",
"Milwaukee", "Broomfield", "Milwaukee", "Mecklenburg", "Chatham",
"Wake", "Grand", "Caldwell", "Wake", "Union", "Milwaukee", "Garfield",
"Ozaukee", "Rutherford", "Wilkes", "Oneida", "Dane", "Cabarrus",
"Adams", "Henderson", "Cumberland", "Davidson", "Weld", "Harnett",
"Seminole", "Rio Grande", "Washington", "Jefferson", "Mecklenburg",
"Davidson", "Guilford", "Onslow", "Pinellas", "Iredell", "Lenoir",
"Wake", "Boulder", "Boulder", "Guilford", "Oneida", "Wake", "Denver",
"Miami-Dade", "Denver", "Waukesha", "Wake", "Eau Claire", "Ozaukee",
"Miami-Dade", "Buncombe", "Palm Beach", "Buncombe", "Polk", "Leon",
"Durham", "Boulder", "Jefferson", "Sampson", "Hillsborough",
"Logan", "Wake", "Union", "Sumter", "Jefferson", "Orange", "Larimer",
"Eau Claire", "Fond du Lac", "Winnebago", "Hillsborough", "Wake",
"Milwaukee", "Larimer", "Hernando", "Chatham", "Pinellas", "Mecklenburg",
"Dane", "Wake", NA, "Jefferson", "Marion", "Durham", "Marathon",
"Wilkes", "Marathon", "Dane", "Wake", "El Paso", "Seminole",
"Mecklenburg", "Outagamie", NA, "Dane", "Onslow", "Brevard",
"Milwaukee", "Kenosha", "Lee", "Martin", "Jefferson", "Hillsborough",
"Gadsden", "Adams", "Seminole", "Burke", "Arapahoe", "El Paso",
"Union", "Milwaukee", "Rutherford", "Dane", "Broward", "Wood",
"Pitt", "Pinellas", "Larimer", "Pinellas", "Denver", "Pinellas",
"Orange", "Buncombe", "Clay", "Milwaukee", "Broward", "Hillsborough",
NA, "Alachua", "Guilford", "El Paso", "Pinellas", "Jefferson",
NA, "Hillsborough", "Dane", "Broward", "Wake", "Winnebago", "Dane",
"Harnett", "Outagamie", "Elbert", "Marathon", "Mesa", "Kenosha",
"Rockingham", NA, "Brown", "Douglas", "Wood", "Rock", "Denver",
NA, "Wake", "Dunn", "Custer", "Mecklenburg", "Durham", "Hillsborough",
"Sarasota", "Arapahoe", "Marion", "El Paso", "Weld", "Weld",
"Waukesha", "Lee", "Polk", "El Paso", "St. Lucie", "Douglas",
"Jefferson", "Calumet", NA, "Adams", "Polk", "Leon", "Johnston",
NA, NA, NA, "Orange", "Arapahoe", "Miami-Dade", "Denver", "Jefferson",
"Miami-Dade", NA, NA, "Sarasota", "Denver", "Douglas", "El Paso",
"Alamance", "Durham", NA, "El Paso", "Vilas", "Jefferson", "Weld",
"St. Johns", NA, "Cabarrus", "Lafayette", "Sarasota", "Miami-Dade",
"Randolph", "Jefferson", "Lafayette", "Lee", "Milwaukee", "Hillsborough",
"Winnebago", NA, "Lee", "Arapahoe", NA, "Arapahoe", NA, "Brown",
"Winnebago", "Douglas", "Wake", NA, "Boulder", "Brevard", "Wake",
"Jefferson", "Dane", NA, "Manitowoc", "Denver", NA, "Arapahoe",
"Larimer", "Milwaukee", "Arapahoe", "Volusia", "Seminole", "Indian River",
"Stokes", "Hillsborough", "Boulder", NA, "Kenosha", NA, "Winnebago",
"Arapahoe", "Weld", "Adams", "Polk", NA, "Brunswick", "Buncombe",
"Nash", "Pasco", "Jefferson", "Arapahoe", NA, "Crawford", NA,
"Cabarrus", "Chatham", NA, "Broward", "Jefferson", NA, NA, "Scotland",
"New Hanover", "Milwaukee", NA, "Sheboygan", "Marion", "Outagamie",
NA, NA, "Douglas", "Orange", "Weld", "Wake", "Denver", "Pinellas",
"Dane", "Arapahoe", "Orange", "Denver", "Denver", "Pasco", "Racine",
"Brevard", NA, "Delta", NA, "Larimer", "Haywood", "Denver", NA,
"El Paso", NA, "Racine", "Wake", NA, "Lee", "Wake", "Broomfield",
"Orange", "Ashland", "Waukesha", NA, "Racine", "Forsyth", "Milwaukee",
"Nash", "Racine", "Boulder", "Weld", "Milwaukee", NA, "Duval",
"Milwaukee", "Cumberland", "Brown", "Duval", "Lincoln", "Guilford",
"Palm Beach", "Jefferson", "Broward", NA, "Boulder", "Duval",
"Douglas", "Grant", "Wake", NA, "Adams", "Leon", "Adams", "Jefferson",
"Larimer", "Portage", "Larimer", "Jefferson", "Dodge", "Forsyth",
"Milwaukee", "Johnston", "New Hanover", "Alleghany", "Winnebago",
"Denver", "Brown", "Dane", "Catawba", "Buncombe", "Miami-Dade",
"Burke", "Mesa", "Miami-Dade", "St. Johns", "Broward", NA, "Ozaukee",
"Waukesha", NA, "Highlands", NA, "Palm Beach", "Lake", "Martin",
NA, "Collier", "Wake", "Teller", "Orange", "Charlotte", "Milwaukee",
"Denver", "Miami-Dade", "Seminole", "Hillsborough", NA, "Columbus",
"Miami-Dade", "Boulder", "Elbert", "Lincoln", NA, "Vernon", "Denver",
"Palm Beach", NA, "New Hanover", "Cabarrus", "Leon", "Cabarrus",
NA, "Adams", "Seminole", "Johnston", "Polk", NA, "Milwaukee",
NA, "Wake", "Adams", "Guilford", "St. Croix", "Leon", "Carteret",
"Wake", "Durham", "Richmond", NA, "Arapahoe", "Forsyth", "Alamance",
"Manitowoc", "Fond du Lac", "Outagamie", NA, NA, "Wayne", "Broward",
"Green", "Racine", "Denver", "Jefferson", "Pasco", "Sumter",
"Orange", NA, "Palm Beach", "Walworth", "Haywood", NA, "Racine",
NA, "Brown", NA, "Mecklenburg", "Larimer", "Broward", "Oconto",
"Denver", "Pinellas", NA, "Fond du Lac", "Orange", NA, "Randolph",
"Guilford", "Forsyth", "Watauga", "Fremont", "Palm Beach", NA,
"El Paso", "Lee", "Broward", NA, "Fremont", "Wilkes", "Milwaukee",
NA, "Cabarrus", "Leon", "Iron", "Palm Beach", "Milwaukee", "Surry",
"Waukesha", "Citrus", NA, NA, "Adams", "El Paso", "Stanly", "Pasco",
"El Paso", "Lake", "Lincoln", "Douglas", "Broward", "Outagamie",
"Waukesha", "Jefferson", "Denver", NA, "Sarasota", "Guilford",
"Santa Rosa", "Sarasota", "Clay", "Lee", NA, "Miami-Dade", "Calumet",
"Mecklenburg", "Sumter", "Larimer", "Jefferson", "Jackson", "Mecklenburg",
"Pueblo", "Henderson", "Jefferson", "Dane", "Polk", NA, "Wake",
"Broward", "Milwaukee", "Johnston", "Forsyth", "Guilford", "Wake",
"Forsyth", "Sarasota", "Shawano", "Fremont", "Marion", "Union",
"Osceola", NA, "Marion", NA, NA, "New Hanover", "Pinellas", NA,
"Halifax", NA, "Marion", "Palm Beach", "Orange", "Brevard", "Lake",
"Durham", "Jefferson", NA, "Jefferson", "Orange", "Fremont",
"Barron", "Hillsborough", "Orange", NA, NA, NA, "El Paso", "Arapahoe",
NA, "Milwaukee", NA, "Boulder", "Arapahoe", "Summit", "Guilford",
NA, "Haywood", NA, "El Paso", NA, "Green", NA, NA, "El Paso",
NA, NA, NA, "Orange", "Brunswick", NA, "Manatee", "Hillsborough",
NA, NA, "Wake", NA, "Milwaukee", NA, "Douglas", "Gulf", "El Paso",
"Dane", NA, "Douglas", NA, NA, "Denver", NA, "Orange", NA, NA,
NA, "Hillsborough", NA, NA, "Leon", "Dane", "Milwaukee", "Outagamie",
"St. Lucie", "Palm Beach", "Weld", "Dane", NA, NA, "Forsyth",
"Arapahoe", NA, NA, "Brown", "La Crosse", "Rusk", "Jefferson",
NA, NA, NA, NA, NA, NA, "Sarasota", "Dane", NA, NA, NA, NA, NA,
NA, NA, NA, NA, NA, NA, "Racine", NA, "Mesa", NA, NA, "Onslow",
"Broward", "Rock", NA, NA, NA, NA, NA, "Harnett", NA, NA, "Milwaukee",
"Charlotte", "Palm Beach", NA, NA, NA, NA, NA, "El Paso", NA,
NA, "Dane", "Alachua", NA, "Palm Beach", NA, "Jefferson", NA,
"Shawano", NA, "Polk", NA, "Adams", "Lake", "Wake", "Boulder",
"Brown", NA, "La Crosse", NA, NA, NA, "Palm Beach", "Waukesha",
"Orange", NA, "Manatee", NA, "Miami-Dade", NA, NA, "St. Johns",
NA, NA, NA, NA, NA, NA, NA, "Arapahoe", NA, "Gulf", "Guilford",
NA, "New Hanover", "Denver", "Douglas", "Washington", NA, "Clark",
NA, NA, "Waukesha", "Miami-Dade", "Jefferson", NA, "Miami-Dade",
NA, "Gaston", NA, "Brevard", NA, NA, "Hillsborough", "Alexander",
"Outagamie", "Douglas", "Douglas", NA, "Gilpin", "Winnebago",
NA, "Douglas", NA, NA, "Pinellas", "Adams", "Seminole", NA, "Hernando",
"Alachua", "Pasco", "Collier", "El Paso", NA, "Person", "Rockingham",
NA, "Seminole", "Marion", NA, "Collier", "Alamance", NA, "Mecklenburg",
"Palm Beach", "El Paso", "Escambia", "Brevard", "Hillsborough",
"Escambia", "Broward", "Seminole", "Palm Beach", "Palm Beach",
NA, "Pinellas", "Osceola", "Escambia", NA, "Collier", "Okaloosa",
NA, "Lake", "Douglas", NA, "Osceola", "Monroe", "Collier", NA,
"Hillsborough", "Orange", "Wakulla", "St. Johns", "Indian River",
"Broward", "Boulder", NA, "Palm Beach", "Palm Beach", "Polk",
"Palm Beach", "Duval", "Pasco", "Orange", "Lake", "Putnam", "Santa Rosa",
"Duval", "Baker", "Pasco", "Lee", NA, "Miami-Dade", "Leon", "Pinellas",
"Hillsborough", "Okaloosa", "Palm Beach", "Hillsborough", "Broward",
"Marion", "Collier", "Manatee", "Denver", "Volusia", "Broomfield",
"Osceola", "Charlotte", "Pinellas", "Sarasota", NA, "Alachua",
NA, NA, "Escambia", "Miami-Dade", NA, NA, "Polk", NA, "Rock",
"Brown", "Denver", "Brevard", "Lake", "Polk", "Volusia", "Weld",
NA, "Sarasota", "Miami-Dade", "Orange", "Broward", "Gilchrist",
"Duval", "Brevard", "Orange", "Broward", NA, NA, "Sarasota",
"Pinellas", "Martin", "Palm Beach", "Bay", "Orange", "Palm Beach",
"Lee", "Leon", "Pasco", "Hillsborough", "Indian River", "Pinellas",
"Suwannee", "Seminole", "Bay", "Broward", NA, NA, "Volusia",
"Polk", "Polk", "Santa Rosa", "Gulf", "Orange", "Volusia", "Lake",
"Walton", "Broward", NA, NA, "Miami-Dade", "Citrus", "Orange",
"Putnam", "El Paso", "Lee", "Pasco", "Lake", "Broward", "Highlands",
"Duval", "Alachua", "Leon", "Bay", "Marathon", "Collier", "Palm Beach",
"Lake", "St. Croix", NA, "Douglas", "Seminole", "Eau Claire",
"Broward", "Alachua", NA, "Polk", "Volusia", "Marion", "Seminole",
"Miami-Dade", "Brevard", NA, "Duval", "Broward", "Palm Beach",
"Charlotte", "Hernando", "Marion", "Leon", "Lake", "Miami-Dade",
"Lee", "Orange", NA, "Indian River", NA, "Mecklenburg", "Miami-Dade",
"Miami-Dade", "Broward", "Volusia", "Dane", "Volusia", "Hillsborough",
"Brevard", "Manatee", "Palm Beach", "Leon", "Catawba", "Lake",
NA, "Okaloosa", "Brown", "Pinellas", "St. Johns", "Sarasota",
"Brevard", "Broward", "Lee", "Volusia", "Marion", "Polk", "Hillsborough",
NA, "Eau Claire", "Monroe", "Person", "Duval", "Orange", NA,
"Pasco", "Broward", "Boulder", "Citrus", "Volusia", "Seminole",
"Sheboygan", "Polk", NA, "Milwaukee", "Pinellas", "Pasco", "Highlands",
"Sarasota", "Pasco", "Alachua", "Hillsborough", "Broward", "Broward",
"Broward", "Brevard", "Broward", "Polk", "St. Lucie", NA, NA,
"Volusia", NA, "Wakulla", "Alachua", "Marathon", NA, "Charlotte",
"Palm Beach", "Denver", "Hernando", "Palm Beach", "Lee", "Broward",
"Brevard", "Broward", "Brevard", "Adams", "Palm Beach", "Bay",
NA, "Manatee", "Seminole", "Alachua", NA, "Miami-Dade", NA, "Brevard",
"Sumter", "Pinellas", "Gulf", "Highlands", "Hillsborough", "Bay",
"Palm Beach", "Milwaukee", "Lee", NA, "Lake", "Lake", "Guilford",
NA, "Escambia", "Palm Beach", "Marion", "Manatee", "Brown", "Seminole",
"Seminole", NA, "Miami-Dade", "Hernando", "Pinellas", "Hillsborough",
"Buncombe", "Hillsborough", "Pinellas", "Palm Beach", "Pinellas",
"Flagler", "Sarasota", "Pasco", "Marion", NA, "Volusia", "Hillsborough",
"Miami-Dade", NA, "Seminole", "Santa Rosa", "Escambia", "Marathon",
"Miami-Dade", "Polk", "Catawba", "Collier", "Seminole", "Hillsborough",
"Miami-Dade", "New Hanover", "Pinellas", "Waukesha", "Hillsborough",
NA, "Lee", NA, "Washington", "Lee", NA, "Escambia", "Hillsborough",
"Volusia", "Pinellas", NA, "Monroe", NA, "Broward", "Santa Rosa",
"Broward", "Orange", NA, "Palm Beach", "Citrus", "Palm Beach",
"Hoke", "Orange", "Lee", "Orange", "Miami-Dade", "Broward", "Pasco",
"Broward", "Brevard", "Broward", "Marion", "Duval", "Sarasota",
"Bay", "Pinellas", "Hillsborough", NA, "St. Lucie", "Citrus",
"Seminole", "Polk", NA, "El Paso", "Escambia", "Duval", "Broward",
"Miami-Dade", NA, "Broward", "Sarasota", "Pinellas", "Moore",
"Seminole", "Marion", "Escambia", "Orange", "Palm Beach", "Palm Beach",
"Volusia", "Sumter", "Bay", "Orange", "Miami-Dade", "Pinellas",
"Hillsborough", "Osceola", "Leon", "Sarasota", "Broward", "Orange",
"Miami-Dade", "Pinellas", "Pinellas", "Durham", "Seminole", "Flagler",
"Milwaukee", "Outagamie", "Bladen", "Osceola", "Duval", NA, NA,
"Broward", "Milwaukee", "Palm Beach", "Volusia", NA, "Volusia",
"Polk", "Miami-Dade", "Alachua", "Broward", "Collier", NA, NA,
NA, "Charlotte", "Palm Beach", "Brevard", "Orange", "Martin",
NA, "Broward", "Brevard", NA, "Okaloosa", "Broward", "Flagler",
"Brevard", "Pinellas", NA, "Pasco", "Hillsborough", "Polk", "Sarasota",
"Palm Beach", NA, "Dane", NA, "Martin", "Broward", "Polk", "Alachua",
"Duval", "Leon", "Pinellas", "Okaloosa", "Charlotte", "Pinellas",
"Escambia", "Palm Beach", "Marion", "Flagler", "Lee", "Lee",
"Miami-Dade", "Miami-Dade", "Orange", "Orange", "Arapahoe", "Orange",
"Orange", "El Paso", "Broward", NA, "Miami-Dade", "Lee", "Duval",
"Pinellas", "Palm Beach", "Citrus", "Dunn", "New Hanover", NA,
"Santa Rosa", "Brevard", "Pasco", "Broward", NA, "Palm Beach",
"Sumter", "Jefferson", NA, NA, "Polk", "Buncombe", "Palm Beach",
"Flagler", NA, "Walton", "Brevard", NA, "Pinellas", NA, "Escambia",
"Volusia", NA, "Marion", "Brevard", NA, "Lee", "Guilford", "Bay",
"Volusia", "Broward", "St. Lucie", "Pinellas", NA, "Guilford",
"Palm Beach", NA, "Duval", "Marion", "Broward", "Madison", "Hillsborough",
"Miami-Dade", "Marinette", "Polk", "Hernando", "Racine", "Palm Beach",
"Seminole", "Highlands", "Alachua", "Manatee", "Broward", "Escambia",
"Okaloosa", NA, NA, "Alachua", "Orange", "Vilas", "Lee", NA,
"Palm Beach", "Clay", "Lee", "Polk", "Okaloosa", "St. Johns",
"St. Lucie", "Pinellas", "Winnebago", "Miami-Dade", NA, "Polk",
"Indian River", "Brevard", "Broward", "Sarasota", "Miami-Dade",
"Larimer", "Clay", "Pasco", NA, "Adams", "Lee", "Manatee", "El Paso",
"Escambia", "Leon", "Palm Beach", NA, "Broward", "Escambia",
"Arapahoe", NA, "Charlotte", "Pinellas", NA, NA, "Miami-Dade",
NA, "Lee", "Pinellas", "Boulder", "Miami-Dade", "Weld", "Iredell",
"Broward", "Bay", "Sarasota", "Orange", "Sumter", NA, "Orange",
"Collier", NA, NA, "Duval", "Madison", "Gilchrist", "Dane", "Dixie",
"Broward", "Sarasota", "Broward", "Miami-Dade", NA, "Clay", NA,
"Lee", NA, "Collier", NA, "Citrus", NA, "Rock", "Weld", "Broward",
"Dane", "Martin", NA, "Flagler", "Pinellas", "Jefferson", "Charlotte",
"Lee", NA, "Leon", "Broward", "Miami-Dade", "Pinellas", "Lee",
"Levy", "Orange", "Marion", "Orange", "Miami-Dade", "Alachua",
"Miami-Dade", "Osceola", "Volusia", "Orange", NA, "Volusia",
"Lee", NA, "Brevard", "Lee", "Broward", "Halifax", "Orange",
NA, NA, "Wakulla", "St. Johns", "Broward", NA, "Palm Beach",
"Santa Rosa", "Pepin", NA, "Wake", "Lee", "Pinellas", "Palm Beach",
"Polk", "Bay", NA, "Citrus", "Seminole", "Hillsborough", "Broward",
"Pinellas", "Brevard", "Pasco", "Dixie", "Broward", "Pasco",
"Wake", NA, "Manatee", "Hillsborough", "St. Lucie", "Larimer",
NA, "Escambia", NA, "Bay", "Lee", "Brevard", "Broward", "Haywood",
"Pinellas", "Sarasota", "Lake", NA, "Wake", "Orange", "Boulder",
"Collier", "Sarasota", "Polk", "St. Johns", NA, NA, "Pinellas",
"Hillsborough", "Pinellas", "Baker", "Okaloosa", NA, NA, "Lee",
NA, "Brevard", NA, NA, "Broomfield", "Martin", NA, "Denver",
"Martin", "Lee", "Palm Beach", "Milwaukee", "Duval", "Gilchrist",
"Indian River", "Weld", "Palm Beach", "Polk", "Broward", "Madison",
"Lee", "Lee", NA, NA, "Craven", NA, NA, "Polk", NA, "Chippewa",
"Miami-Dade", "Hillsborough", "Seminole", "Marion", "Okaloosa",
"Mecklenburg", NA, "Pinellas", "Marion", "Cumberland", NA, "St. Lucie",
"Hillsborough", "Sarasota", "Broward", "Pinellas", "Orange",
NA, "Pinellas", "Jackson", "Palm Beach", "Martin", "Sarasota",
"Miami-Dade", "Alachua", "Milwaukee", NA, "Milwaukee", "Broward",
"St. Johns", "Sumter", "Collier", "Mecklenburg", NA, "Pitt",
"Pasco", "St. Johns", "Pinellas", "Indian River", "Hillsborough",
"Orange", "Hillsborough", "Palm Beach", NA, NA, "Volusia", NA,
"Sarasota", "Hillsborough", "Palm Beach", "Hillsborough", "St. Johns",
NA, "Sarasota", "Brevard", "Pinellas", "Hernando", "Miami-Dade",
"Mesa", "Lake", "Hillsborough", "Polk", "Manatee", NA, "Seminole",
"Polk", "Mecklenburg", "Broward", NA, "Pasco", "Flagler", "Marion",
"Orange", "Miami-Dade", "Marion", "Arapahoe", NA, NA, "Clay",
"Dane", "Martin", "La Plata", "Durham", "Brevard", "El Paso",
"Milwaukee", "Volusia", "Guilford", "Martin", "Jefferson", "Denver",
"Lake", "Duval", NA, "Wood", "Archuleta", NA, "Broward", NA,
"Polk", "Manatee", NA, "Leon", NA, NA, "Duval", "Bay", "Lee",
"Broward", "Volusia", "Broward", "Alachua", NA, NA, "Cabarrus",
"Marion", "Miami-Dade", NA, "Orange", "Hillsborough", "Pinellas",
"Escambia", "Marion", "Hernando", "Sarasota", "Washington", "St. Johns",
"Randolph", "Pinellas", "Volusia", "Pinellas", "Volusia", "Broward",
"Miami-Dade", "Broward", "Pasco", "Miami-Dade", "Larimer", "Bay",
NA, "Duval", "Pueblo", "Broward", "Osceola", NA, "Broward", "Miami-Dade",
"Broward", NA, "Pasco", "Pinellas", "Pinellas", NA, "Walton",
"Sumter", "Orange", "Clay", NA, "Miami-Dade", "Volusia", NA,
"Okaloosa", "Palm Beach", "Larimer", "Hillsborough", "Seminole",
"Martin", "Santa Rosa", "St. Johns", "Volusia", "Orange", "Escambia",
"Citrus", NA, "Brevard", "Alachua", "Okaloosa", "Pinellas", NA,
"St. Johns", "Seminole", NA, "Volusia", NA, "Brunswick", "Polk",
"Guilford", NA, "Pinellas", NA, "Alachua", "Lake", NA, "Pasco",
"Volusia", "Duval", "Gadsden", "El Paso", "Pinellas", "Leon",
"Sumter", "Orange", "Forsyth", NA, "Escambia", NA, "Alamance",
NA, "Highlands", "Palm Beach", "Broward", "Pinellas", "Lee",
"Gilchrist", "Orange", "Duval", "Palm Beach", "Broward", "Orange",
"Orange", "Jefferson", "Seminole", "Manatee", "Hillsborough",
"Adams", "Orange", "Arapahoe", "Duval", "Guilford", "Denver",
"Brevard", "Broward", "Mecklenburg", "Palm Beach", "Highlands",
"St. Lucie", NA, NA, NA, "Palm Beach", NA, "Jefferson", "Adams",
"Miami-Dade", "Collier", NA, "Orange", "El Paso", "Broward",
NA, "Alachua", NA, "Hernando", "Leon", "Lake", "Orange", NA,
"Sumter", NA, "Seminole", "St. Johns", "El Paso", "Boulder",
"Clay", "Lee", "Miami-Dade", "Denver", "Pinellas", NA, "Manatee",
"Suwannee", NA, "Broward", "Weld", "Hillsborough", NA, "Pasco",
"Polk", NA, NA, "Okaloosa", "Marion", "Broward", "Nassau", "Duval",
NA, "Hardee", "Lee", "St. Johns", "Pinellas", "Palm Beach", "Osceola",
"Hillsborough", "Seminole", "Lake", "Lee", NA, "Sarasota", "Seminole",
"Seminole", "Palm Beach", NA, "Orange", "Orange", "Duval", "Richmond",
"Duval", "Indian River", "Santa Rosa", "Lake", "Miami-Dade",
"St. Lucie", "Volusia", "Gadsden", "Sarasota", "Duval", "Pinellas",
"Seminole", "Bay", "Hernando", "Broward", "Palm Beach", "St. Johns",
"Palm Beach", "Duval", "Broward", "Manatee", "Broward", "Manatee",
NA, "Pasco", "Pasco", "Sarasota", "Suwannee", "Putnam", "Lee",
"Seminole", "Broward", "Flagler", "Citrus", "Clay", NA, "Manatee",
"Wake", "Palm Beach", NA, "Pasco", "Broward", "Palm Beach", NA,
"Hernando", "Lee", "Seminole", "Pinellas", NA, "Broward", "Collier",
NA, "Sarasota", "Onslow", "Sumter", NA, "Duval", NA, "Waukesha",
NA, "Hillsborough", "Duval", "Orange", NA, "Hillsborough", "Orange",
"Miami-Dade", "Collier", "Pinellas", "Durham", "Pasco", NA, "Hillsborough",
"Miami-Dade", "Broward", "Manatee", NA, "Volusia", "Lake", NA,
NA, "Collier", "Duval", "Lake", "Broward", "Escambia", "Hillsborough",
"Indian River", "Orange", "Duval", "Okaloosa", "Broward", "St. Johns",
"Palm Beach", "Marion", "Miami-Dade", "Nassau", "Manatee", "Nash",
"Orange", "Palm Beach", "Broward", "Miami-Dade", "Marion", "Broward",
"Manatee", "Brevard", "Sarasota", NA, "Volusia", NA, "Broward",
"Alachua", "Citrus", "Pinellas", "Highlands", "St. Lucie", "Wakulla",
"Marion", "Marion", "Polk", "Seminole", "Hernando", "Brevard",
"Volusia", "Palm Beach", "Orange", "Brevard", NA, "Pasco", "Sumter",
"Broward", NA, "Palm Beach", "Brevard", "Broward", "Broward",
"Palm Beach", "Polk", "Broward", "DeSoto", NA, "Brevard", "Palm Beach",
"Brevard", "Broward", "Palm Beach", "Indian River", "Flagler",
NA, "Citrus", "Orange", "Osceola", "Clay", "Wakulla", "Leon",
NA, NA, "Orange", NA, NA, "Brevard", "Indian River", "Brevard",
NA, "Sumter", "Monroe", "Hillsborough", "Okaloosa", "Sarasota",
"Wood", "Volusia", "Collier", "Orange", "Hernando", "Sarasota",
"Orange", "Highlands", NA, "Sarasota", "Alachua", "Sumter", "St. Lucie",
"Hillsborough", "Lee", "Polk", "Hillsborough", NA, "Hernando",
"Lake", "Rock", "Suwannee", "Manatee", "Hillsborough", "Orange",
"Palm Beach", NA, "Duval", "Palm Beach", "Orange", "Seminole",
"Seminole", NA, "Marion", "Orange", NA, "Osceola", "St. Johns",
"Volusia", NA, "Miami-Dade", NA, "Miami-Dade", "Pinellas", "Pinellas",
"St. Johns", "Jefferson", "Orange", "Osceola", "Palm Beach",
"Mecklenburg", "Brevard", "Marion", "Putnam", "Collier", "Miami-Dade",
"Orange", "Broward", "Hillsborough", "Volusia", "Lee", "Hillsborough",
"Miami-Dade", "Pasco", "Broward", "Palm Beach", "Broward", "Seminole",
"Brevard", "Palm Beach", "Arapahoe", "Palm Beach", "Citrus",
"Clay", "Pinellas", "Sarasota", "Volusia", "Duval", "Pasco",
"Brevard", "Palm Beach", "Orange", "Duval", "Volusia", "Indian River",
"Lee", "St. Johns", "Duval", "Lee", "Sarasota", "Highlands",
"Brevard", NA, "Polk", "Indian River", NA, NA, NA, "Orange",
"Palm Beach", "Palm Beach", "Miami-Dade", NA, "Orange", "Orange",
"Broward", "St. Johns", "Miami-Dade", "Manatee", "Palm Beach",
"Sarasota", "Pinellas", "Orange", "Lee", "Lee", NA, "Sarasota",
"Volusia", "Marion", NA, "Wake", "Martin", "Pinellas", "Miami-Dade",
NA, "Marion", "Mecklenburg", "Manatee", "Broward", "Palm Beach",
"Citrus", NA, "Gadsden", "Volusia", NA, "Sumter", "Leon", NA,
NA, "Osceola", "Martin", "Manatee", "Orange", "Duval", "Lake",
"Palm Beach", "Polk", "Palm Beach", "Escambia", "Lee", "Broward",
"Broward", "Pasco", NA, "Union", "Broward", NA, "Pinellas", "Escambia",
"Manatee", NA, NA, "Sarasota", "St. Lucie", NA, "Duval", "Martin",
"Hillsborough", "Broward", "Volusia", "Lee", "Manatee", "Orange",
"Palm Beach", "Polk", "Marion", "Manatee", "Pinellas", "Washington",
"Miami-Dade", "Hillsborough", "Leon", "Palm Beach", "Santa Rosa",
"Manatee", "Sarasota", "Volusia", "Polk", "Flagler", "Manatee",
"Palm Beach", NA, "Manatee", NA, "Sarasota", "Pinellas", NA,
"Pinellas", "St. Johns", "Hillsborough", "Broward", "Hillsborough",
"Manatee", "Marion", "Pinellas", "St. Lucie", "Alachua", "Palm Beach",
NA, "Hillsborough", NA, NA, "Volusia", "Duval", NA, NA, "Wake",
"Seminole", "Broward", "Palm Beach", "Lake", NA, "Broward", "Franklin",
"St. Johns", "Broward", "Mecklenburg", "Nassau", "Rock", NA,
"Wake", "Hillsborough", "Leon", "St. Lucie", "Indian River",
"Sarasota", NA, NA, "Duval", "Indian River", "Brevard", "Marion",
"Duval", "Mecklenburg", "La Crosse", "Winnebago", NA, NA, "Volusia",
"Lake", "Henderson", NA, "Duval", "Palm Beach", "Okeechobee",
"Broward", NA, "Broward", "Palm Beach", NA, "Escambia", "Chippewa",
NA, "Pinellas", "Avery", "Lee", "Martin", "Palm Beach", "Dane",
"Mecklenburg", NA, "Durham", "Milwaukee", "Durham", "Palm Beach",
"Buncombe", "Lake", "El Paso", NA, "Dixie", "Clay", "Lee", "Outagamie",
NA, "Hillsborough", "Gaston", NA, "Davidson", "Citrus", "Dane",
"Pender", "Brevard", "Polk", "Pinellas", "Lee", NA, "Wake", "Iredell",
"Hernando", "Mecklenburg", "Alachua", "Milwaukee", "Gilchrist",
"Portage", "Charlotte", NA, NA, "Anson", "Duval", "Marion", "Jefferson",
"Broward", "Wake", "Miami-Dade", "Johnston", "Miami-Dade", "Polk",
"Pinellas", "Cabarrus", "Catawba", NA, NA, "Broward", "Brevard",
"Polk", "Buncombe", NA, "Manatee", "St. Johns", "Wake", "Flagler",
"Dane", "Pasco", "Iredell", "Highlands", "Waukesha", "Brevard",
"Dane", "Broward", NA, "Volusia", "Lee", "Pueblo", "Lee", NA,
"Hillsborough", "Manatee", "Okaloosa", "Winnebago", "Rowan",
"Walworth", "Milwaukee", "Seminole", "Lee", "Hillsborough", "Escambia",
"Broward", "New Hanover", "Miami-Dade", "St. Lucie", NA, NA,
"Lee", "Palm Beach", "Miami-Dade", "Arapahoe", NA, "Palm Beach",
"Pinellas", "Lincoln", "Wake", "Sumter", "Rowan", "Vance", "Nassau",
NA, "Pinellas", "Guilford", "Brevard", "St. Johns", "Palm Beach",
NA, "Union", "Hernando", "Manatee", "Brevard", "Pasco", "Leon",
"Guilford", "Pasco", "Miami-Dade", "Escambia", "Watauga", "Madison",
"Miami-Dade", NA, NA, "Polk", "Pinellas", "Hillsborough", "Hardee",
"Dane", "Orange", "Mecklenburg", "Jefferson", NA, "Hendry", NA,
"Orange", NA, "Guilford", "Volusia", "Leon", "Charlotte", "Hillsborough",
NA, "Palm Beach", NA, "Volusia", "Buncombe", "Palm Beach", "Wake",
NA, "Miami-Dade", NA, "Palm Beach", "Monroe", "Miami-Dade", "Brown",
"Sarasota", "Orange", "Marion", "Pasco", "Fremont", "Pasco",
NA, "Jefferson", "Lee", NA, NA, NA, NA, "Broward", "Wake", "El Paso",
"Alachua", "Miami-Dade", "Flagler", "St. Lucie", "Rowan", "Cabarrus",
"Outagamie", "Mecklenburg", NA, "Orange", "Hillsborough", "Lee",
"St. Lucie", "Wake", "Duval", NA, "Pinellas", "Palm Beach", "Carteret",
"Broomfield", "Milwaukee", "Milwaukee", "Osceola", "Seminole",
"Bay", "Milwaukee", "Forsyth", "Lake", "Columbia", NA, "Hernando",
"Wake", "Collier", "Mecklenburg", "Flagler", "El Paso", "Duval",
NA, "Pinellas", NA, "Mecklenburg", NA, "Buncombe", "Broward",
"Wake", NA, "Santa Rosa", "Mesa", "Lee", "Eau Claire", "Hillsborough",
"Pitt", "Orange", "Volusia", "Escambia", "Okaloosa", "Palm Beach",
NA, "Polk", "Leon", "Mecklenburg", "Santa Rosa", "Marion", NA,
"Catawba", "Broward", "Alamance", "Lee", "Rockingham", NA, "Miami-Dade",
"Hillsborough", "Waukesha", NA, "Palm Beach", "Alachua", "New Hanover",
"Mecklenburg", "Sarasota", "St. Johns", "Boulder", NA, "Weld",
"Boulder", "Denver", "Collier", "Charlotte", "Brunswick", "Henderson",
"Pasco", "Polk", NA, "Milwaukee", "Virginia Beach city VA", "Duval",
"Escambia", "Lee", "Milwaukee", "Waukesha", "Escambia", NA, "Sumter",
"Wood", NA, "Seminole", "Sarasota", "Brunswick", "Charlotte",
"Mitchell", "Mecklenburg", "Martin", "Charlotte", "Hillsborough",
"Dunn", NA, "St. Lucie", "Hernando", "Dane", "Seminole", "Polk",
"Osceola", "Denver", "Manatee", "Brevard", "Mecklenburg", "Lake",
"Mecklenburg", "Palm Beach", "Sarasota", "Pasco", "Sarasota",
"New Hanover", "Cabarrus", "Hernando", "Denver", NA, "Hillsborough",
NA, "Brevard", "Hillsborough", "Indian River", "Adams", "Charlotte",
"Marion", "Flagler", "Dane", NA, NA, "Dane", NA, "Arapahoe",
NA, "Charlotte", "Pinellas", "Buncombe", "Brevard", NA, "Randolph",
"Mesa", "Nassau", "Milwaukee", "Denver", NA, "Lee", "Cumberland",
NA, "Jefferson", NA, "Volusia", "Dane", NA, "Duval", "Waukesha",
"Seminole", NA, "Arapahoe", "Orange", "Haywood", "Vernon", "Douglas",
"Miami-Dade", "St. Johns", NA, "Collier", "Cabarrus", "Duval",
"Volusia", "Broward", "Flagler", "Palm Beach", "Orange", NA,
"Seminole", NA, "Person", "Martin", "Ashe", "Broward", "Pasco",
"Palm Beach", NA, NA, "Sarasota", "Lake", "Wake", "Santa Rosa",
NA, "Guilford", "Orange", "Lee", "Waukesha", NA, "Duval", "Burke",
"Orange", "Miami-Dade", "Buncombe", "Leon", "Dane", NA, "Marion",
"Cumberland", "Wake", "Martin", NA, NA, "Martin", "Guilford",
"Pinellas", "Broward", "Bay", "Hillsborough", "Duval", NA, "Jefferson",
"Sumter", "Hillsborough", "Hillsborough", "Pinellas", "Jackson",
"Duval", "Alamance", "Wakulla", "Flagler", "Brevard", "Monroe",
"Miami-Dade", NA, "Polk", "Pasco", "Buncombe", "Citrus", "El Paso",
"Pinellas", NA, "Orange", "Hillsborough", "Broward", "Broward",
"Manitowoc", "Seminole", "Catawba", NA, "Washington", "Hillsborough",
"Lake", "St. Johns", "Denver", "Dane", "Palm Beach", "Broward",
"Weld", "Volusia", "Buncombe", "Denver", "Hernando", "Highlands",
"Ozaukee", "Collier", "Douglas", "Wake", "Broward", "La Crosse",
"Pinellas", "Jackson", "Sarasota", "Outagamie", "Jefferson",
"Manatee", "Duval", "Palm Beach", NA, NA, "Pinellas", "Broward",
NA, "Mecklenburg", "Lee", "Brevard", "Onslow", "Suwannee", NA,
"Marion", NA, "Lake", NA, "Volusia", "Alamance", "Polk", "Highlands",
"Pinellas", "Sarasota", "Sarasota", "Orange", "Craven", "Broward",
"New Hanover", NA, "Hillsborough", "Waukesha", "Forsyth", "Brown",
"Hillsborough", "Alleghany", "Waukesha", "Milwaukee", "Hillsborough",
"La Plata", "Lee", "Pinellas", "Cumberland", "Palm Beach", "Broward",
"Broward", "Broward", "Miami-Dade", "Miami-Dade", NA, NA, "Seminole",
"Palm Beach", "Duval", "Dane", "Volusia", "Martin", "Duval",
NA, "El Paso", "Larimer", NA, "Pinellas", "Chatham", "Pasco",
"St. Johns", "Sarasota", NA, "Miami-Dade", NA, "Wake", "Marion",
"Hillsborough", "El Paso", "Brunswick", "Broward", "Palm Beach",
"Guilford", "Palm Beach", "Duval", "Broward", NA, NA, "Duval",
NA, "Marion", "Arapahoe", "Palm Beach", "Martin", NA, "Adams",
"St. Johns", "Dodge", "Seminole", "Duval", "Miami-Dade", "Brevard",
"Orange", "Escambia", "Brevard", "Lee", "Mecklenburg", "Martin",
"Palm Beach", "Orange", "Volusia", "Lee", "Buncombe", "Palm Beach",
"Jackson", "Dane", "Volusia", "Arapahoe", "Palm Beach", "Palm Beach",
NA, NA, NA, NA, "Okaloosa", NA, "Hillsborough", "Mecklenburg",
"Lee", NA, "Polk", "Palm Beach", "Taylor", "Wake", "Pitt", "Arapahoe",
"Orange", "Sarasota", "Manatee", NA, "Volusia", "Columbia", "Broward",
NA, "Jefferson", "Walworth", "Denver", "Douglas", NA, "Jefferson",
"Jefferson", "Miami-Dade", "Winnebago", NA, "Brevard", "Hillsborough",
"Volusia", "Volusia", "Broward", "Mecklenburg", "Polk", "Lee",
"Volusia", "Bay", NA, "Cumberland", "Polk", NA, NA, "Collier",
"Duval", NA, "Pinellas", "Forsyth", NA, "St. Lucie", "St. Lucie",
"Dane", "Sarasota", "Union", "Iredell", "Fond du Lac", "Seminole",
"Dane", "Escambia", "Mecklenburg", "El Paso", NA, "Monroe", "Citrus",
"Lincoln", "Broward", "Pasquotank", "Milwaukee", NA, "Rockingham",
"Davidson", "Palm Beach", NA, "Fond du Lac", "Lake", "Wake",
NA, "Marion", "St. Johns", "Orange", "Alachua", NA, "Sarasota",
"Denver", "Gunnison", "Hillsborough", "Manatee", NA, "Milwaukee",
"Pinellas", NA, "Orange", "Walworth", "Denver", "Wake", "Caldwell",
"Miami-Dade", "El Paso", "Milwaukee", "Palm Beach", "Lee", "St. Johns",
"Granville", "Polk", "Highlands", "Jefferson", "Guilford", "Larimer",
"Harris TX", "St. Lucie", "Pinellas", "Palm Beach", "Levy", "Anson",
"Pasco", "Lake", "Douglas", "Pinellas", NA, "Broward", "Marion",
"Palm Beach", NA, "Pinellas", "Ashland", "Wake", "Polk", "Pender",
NA, NA, "Broward", "Adams", NA, "Manatee", "Hillsborough", "Mecklenburg",
"Craven", "Duval", "Brevard", NA, "Putnam", "Mecklenburg", "Indian River",
"Lincoln", "St. Lucie", "Marion", "Boulder", "Waukesha", "Seminole",
"Duval", "Pinellas", "Orange", "Adams", "Orange", "Hernando",
"Wake", "Mecklenburg", "Lee", "Denver", "Palm Beach", NA, "Guilford",
"Weld", "Granville", "Collier", NA, "Flagler", "Sarasota", NA,
"Marion", "Grand", "Burnett", "Okeechobee", NA, "St. Johns",
NA, "Sumter", "Miami-Dade", "Sarasota", "Miami-Dade", "Monroe",
NA, NA, "Volusia", "Marion", NA, NA, NA, "Marion", "Monroe",
"Pasco", NA, NA, "Buncombe", "Sarasota", "Escambia", NA, "Lee",
"Jefferson", "Broward", "Milwaukee", "Suwannee", NA, "Davidson",
"Price", NA, "Miami-Dade", "Manatee", "Wayne", "Broward", "Jefferson",
"Polk", "Martin", "Stokes", "Broward", "Marion", NA, NA, "Pasco",
"Dodge", "Palm Beach", "Pasco", "Lenoir", "Denver", "Vilas",
NA, NA, "Miami-Dade", "Orange", "Orange", "Pueblo", "Gadsden",
"Monroe", "Hillsborough", "Broward", "Orange", "Palm Beach",
NA, "Buncombe", "Lincoln", NA, "Moore", "Dane", "Alachua", "Union",
"Pinellas", NA, "Escambia", NA, "Buncombe", NA, "Brevard", NA,
NA, "Waukesha", NA, "Mesa", "Marion", NA, NA, "Charlotte", "Okaloosa",
NA, "Miami-Dade", "Pasco", "Hillsborough", "Polk", "Brevard",
"Milwaukee", "Chatham", "Sarasota", "Chippewa", "Collier", "Caswell",
"Ozaukee", "El Paso", "New Hanover", NA, "Miami-Dade", "Boulder",
"Guilford", "Dane", "Wake", NA, "Lee", NA, "Stanly", "Charlotte",
"Union", "Johnston", "Broward", "El Paso", "Brunswick", "Marion",
"Hillsborough", "Orange", "Guilford", "Trempealeau", "Mecklenburg",
"Dane", "Pitt", "Racine", "Adams", "Ashland", "Broward", "Onslow",
"Pasco", "Volusia", "Broward", NA, NA, "Orange", "Pinellas",
"St. Johns", "Boulder", "Boulder", "Brunswick", NA, "Carteret",
"Polk", NA, NA, NA, "Volusia", "Logan", "Alexander", "Dane",
NA, NA, "Charlotte", "Broward", "Brown", "Volusia", NA, "Sumter",
NA, "Seminole", "Adams", NA, "Douglas", NA, "Lee", NA, "El Paso",
"Ashland", "Volusia", "Seminole", "Mecklenburg", "Duval", "Milwaukee",
NA, "Douglas", NA, "Broward", "Duval", "Citrus", NA, "Mecklenburg",
"Broward", "Guilford", "Escambia", "Denver", "Durham", NA, "Pinellas",
"Brevard", "Cumberland", "Martin", "Brevard", "Fond du Lac",
"Racine", "Winnebago", "Dane", NA, "Kenosha", "Pinellas", "Palm Beach",
"Palm Beach", "Sarasota", "Forsyth", "Miami-Dade", "Durham",
"Broward", "Seminole", "Pinellas", "Santa Rosa", "Pasco", "Wood",
"Jefferson", "Kenosha", "Oconto", "Washington", "Orange", NA,
"Polk", "Volusia", "Manitowoc", "Orange", NA, "Brevard", "Davidson",
NA, "Alachua", NA, "Mecklenburg", "Marion", NA, "Douglas", "St. Lucie",
"Sarasota", "Union", "Arapahoe", "Polk", "Brevard", "Buncombe",
"Broward", "Transylvania", NA, "Gaston", "Volusia", "La Crosse",
"Union", "Pasco", "Lee", "Arapahoe", "Hernando", "Brevard", "Broward",
"Racine", "Iredell", "Hillsborough", NA, "Lee", "Pinellas", NA,
"Duval", "Hernando", "Pasco", NA, "Seminole", "Escambia", "Pinellas",
"Kenosha", "Jefferson", NA, "Palm Beach", "Lincoln", "Martin",
"St. Johns", "Pinellas", NA, "Hillsborough", "Lincoln", "El Paso",
"Chatham", "Orange", "Lenoir", "Lake", NA, NA, "Marion", "Orange",
"Wake", NA, "Mecklenburg", NA, "Palm Beach", "Mecklenburg", "Miami-Dade",
"Orange", NA, "Palm Beach", "Hertford", "Brevard", NA, "Hillsborough",
"Door", "Sarasota", NA, "Waukesha", NA, NA, "Arapahoe", NA, "Escambia",
"Miami-Dade", "Pasco", "Jefferson", "Pinellas", NA, "Hillsborough",
"Johnston", "Indian River", NA, "Columbus", "Henderson", "Dixie",
"Marion", "Hillsborough", "Montezuma", "Osceola", "Pinellas",
"Broward", "Broward", "Orange", "Pinellas", "Wake", NA, "Volusia",
"Sarasota", NA, "Columbia", "Duval", "Bay", "Watauga", "Seminole",
"Boulder", NA, "Waukesha", "Waukesha", NA, NA, "Jefferson", "Cumberland",
"Pinellas", "Osceola", "Duval", "Hernando", NA, NA, "Pinellas",
"Arapahoe", "Bay", NA, "Guilford", "Manatee", "Alachua", NA,
"Broward", "Lake", NA, NA, NA, NA, "Winnebago", "Volusia", NA,
NA, "Osceola", "Waupaca", "Miami-Dade", "Pinellas", "Pasco",
"Lake", "Palm Beach", NA, "Okaloosa", "Weld", "Broward", "Pinellas",
"Dane", "Brevard", "Hillsborough", NA, NA, NA, NA, NA, NA, "Wayne",
NA, "Clear Creek", "Pinellas", "Charlotte", "Marion", "Highlands",
"Manatee", "Rowan", "Racine", "Denver", "Davidson", "Sumter",
"St. Johns", "Denver", "Sheboygan", "Manatee", "La Crosse", "Vance",
NA, "Broward", NA, NA, "Gaston", "Nassau", "Pasco", "Orange",
"Alexander", NA, NA, NA, "Burke", "Orange", NA, "Broward", "Broward",
"Collier", "Lee", "Jefferson", "Citrus", "Sheboygan", "Pasco",
"Oconto", NA, "Lee", "Hillsborough", "Polk", "Manatee", "Clay",
"Jefferson", "Wake", NA, "Orange", "Indian River", "Summit",
"St. Johns", "Beaufort", "Miami-Dade", "Broward", "Sumter", "St. Lucie",
"Palm Beach", "Harnett", "Hillsborough", "Santa Rosa", NA, "Eau Claire",
"Hernando", "Brevard", "Jefferson", NA, "Marion", "Brevard",
"Buncombe", "Miami-Dade", "Polk", "Collier", "Pasco", "Lee",
NA, "Volusia", "Volusia", "Palm Beach", "St. Johns", "Palm Beach",
"Citrus", NA, "Orange", "Pender", "El Paso", NA, "Arapahoe",
"Dodge", NA, NA, "Forsyth", "Pinellas", NA, NA, NA, "Osceola",
NA, "El Paso", NA, "Arapahoe", "El Paso", NA, "Palm Beach", "Rock",
"Buncombe", "Denver", NA, "Green", "St. Croix", NA, "Boulder",
"Fremont", "Pinellas", "Franklin", "Henderson", "Pasco", "Pasco",
"Arapahoe", "Teller", "Palm Beach", "Volusia", "Mecklenburg",
NA, "La Crosse", "Pasco", NA, "Jefferson", NA, "Wake", "Polk",
NA, "Milwaukee", "Mecklenburg", NA, "Davidson", "St. Johns",
"Sarasota", "Davidson", "Collier", "Collier", "Miami-Dade", "Waukesha",
"Larimer", "Broward", "St. Lucie", "Duval", "Denver", NA, "Kenosha",
"Miami-Dade", "Polk", NA, "Sauk", NA, NA, "Adams", "Henderson"
)
