structure(list(url = "https://app.crunch.io/api/sources/", status_code = 201L, 
    headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
        `content-encoding` = "gzip", `content-type` = "application/json;charset=utf-8", 
        date = "Mon, 14 May 2018 15:11:58 GMT", location = "https://app.crunch.io/api/sources/a62b43/", 
        server = "nginx", `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
        `x-timing` = "", `content-length` = "86", connection = "keep-alive"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/1.1", 
        headers = structure(list(allow = "GET, HEAD, OPTIONS, POST", 
            `content-encoding` = "gzip", `content-type` = "application/json;charset=utf-8", 
            date = "Mon, 14 May 2018 15:11:58 GMT", location = "https://app.crunch.io/api/sources/a62b43/", 
            server = "nginx", `set-cookie` = "REDACTED", vary = "Cookie, Accept-Encoding", 
            `x-timing` = "", `content-length` = "86", connection = "keep-alive"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".crunch.io", 
        flag = TRUE, path = "/", secure = FALSE, expiration = structure(1557846718, class = c("POSIXct", 
        "POSIXt")), name = "token", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"element\": \"shoji:view\", \"self\": \"https://app.crunch.io/api/sources/\"}"), 
    date = structure(1526310718, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.8e-05, 
    connect = 5.1e-05, pretransfer = 0.000231, starttransfer = 0.00025, 
    total = 0.490486)), class = "response")
