structure(list(url = "/api/sources/", status_code = 201L, headers = structure(list(
    date = "Thu, 21 Nov 2024 18:53:51 GMT", `content-type` = "application/json;charset=utf-8", 
    `content-length` = "87", location = "/api/sources/db16cc/", 
    server = "CherryPy/18.9.0", allow = "GET, HEAD, OPTIONS, POST", 
    vary = "Cookie, Accept-Encoding", `x-frame-options` = "DENY", 
    `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
    `x-content-type-options` = "nosniff", `x-timing` = "", `content-encoding` = "gzip"), class = c("insensitive", 
"list")), all_headers = list(list(status = 201L, version = "HTTP/2", 
    headers = structure(list(date = "Thu, 21 Nov 2024 18:53:51 GMT", 
        `content-type` = "application/json;charset=utf-8", `content-length` = "87", 
        location = "/api/sources/db16cc/", server = "CherryPy/18.9.0", 
        allow = "GET, HEAD, OPTIONS, POST", vary = "Cookie, Accept-Encoding", 
        `x-frame-options` = "DENY", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `x-content-type-options` = "nosniff", `x-timing` = "", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = logical(0), 
    flag = logical(0), path = logical(0), secure = logical(0), 
    expiration = structure(numeric(0), class = c("POSIXct", "POSIXt"
    )), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"element\": \"shoji:view\", \"self\": \"/api/sources/\"}"), 
    date = structure(1732215231, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 1.4e-05, 
    connect = 0, pretransfer = 0.000182, starttransfer = 0.20746, 
    total = 0.207506)), class = "response")
