structure(list(url = "/api/sources/", status_code = 201L, headers = structure(list(
    date = "Fri, 07 Feb 2020 20:16:26 GMT", `content-type` = "application/json;charset=utf-8", 
    `content-length` = "86", location = "/api/sources/605d4e/", 
    server = "nginx", `content-encoding` = "gzip", vary = "Cookie, Accept-Encoding", 
    allow = "GET, HEAD, OPTIONS, POST", `x-timing` = "", `set-cookie` = "REDACTED"), class = c("insensitive", 
"list")), all_headers = list(list(status = 201L, version = "HTTP/2", 
    headers = structure(list(date = "Fri, 07 Feb 2020 20:16:26 GMT", 
        `content-type` = "application/json;charset=utf-8", `content-length` = "86", 
        location = "/api/sources/605d4e/", server = "nginx", 
        `content-encoding` = "gzip", vary = "Cookie, Accept-Encoding", 
        allow = "GET, HEAD, OPTIONS, POST", `x-timing` = "", 
        `set-cookie` = "REDACTED"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = ".crunch.io", 
    flag = TRUE, path = "/", secure = FALSE, expiration = structure(1612642586, class = c("POSIXct", 
    "POSIXt")), name = "token", value = "REDACTED"), row.names = c(NA, 
-1L), class = "data.frame"), content = charToRaw("{\"element\": \"shoji:view\", \"self\": \"/api/sources/\"}"), 
    date = structure(1581106586, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.4e-05, 
    connect = 3.6e-05, pretransfer = 2e-04, starttransfer = 0.000208, 
    total = 0.55748)), class = "response")
