app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(search = "G")
app$snapshot()
app$setInputs(search = "")
app$setInputs(selected_vars = "Gender")
app$setInputs(selected_vars = c("Gender", "Categorical Location"))
app$setInputs(obj_name = "obj")
app$setInputs(var_name = "new")
app$setInputs(var_name = "newBV")
app$setInputs(var_name = "new")
app$setInputs(var_name = "newVar")
app$snapshot()
