#!/bin/sh
#
# Checks if any files have been updated in the mocks/ directory, if they have
# then it makes a new .tgz archive of that directory and adds it before the
# commit is finished. This should ensure that inst/mocks.tgz is always in sync
# with mocks/
#

mocksUpdated=`git diff --cached --name-only --diff-filter=ACM mocks/`

# IFF files in mocks/ have changed then compress, and add the archive
if [ ${#mocksUpdated} -gt 0 ]
then
	echo "It looks like there are new fixtures."
	echo "Compressing them now: this could take a few seconds."
	make compress-fixtures
	git add inst/mocks.tgz
	echo "Fixtures compressed: inst/mocks.tgz"
fi

