structure(list(url = "/api/projects/264e6b/", status_code = 201L, 
    headers = structure(list(date = "Mon, 03 Mar 2025 17:55:16 GMT", 
        `content-type` = "application/json;charset=utf-8", `content-length` = "0", 
        location = "/api/projects/711d98/", server = "CherryPy/18.9.0", 
        allow = "DELETE, GET, HEAD, OPTIONS, PATCH, POST", vary = "Cookie, Accept-Encoding", 
        `x-frame-options` = "DENY", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `x-content-type-options` = "nosniff"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/2", 
        headers = structure(list(date = "Mon, 03 Mar 2025 17:55:16 GMT", 
            `content-type` = "application/json;charset=utf-8", 
            `content-length` = "0", location = "/api/projects/711d98/", 
            server = "CherryPy/18.9.0", allow = "DELETE, GET, HEAD, OPTIONS, PATCH, POST", 
            vary = "Cookie, Accept-Encoding", `x-frame-options` = "DENY", 
            `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
            `x-content-type-options` = "nosniff"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1741024516, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 1.2e-05, 
    connect = 0, pretransfer = 9.1e-05, starttransfer = 0.29118, 
    total = 0.291223)), class = "response")
