on: push

name: cube-compression

jobs:
  cube-compression:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Check for new changes to cube directory and commit
        run: |
            if git log -n 1 --pretty=format:%H -- inst/cubes.tgz | xargs  git diff --name-only --diff-filter=ADMR $1 | grep -q inst/cubes/
            then
                echo "Compressing"
            	make compress-fixtures
                git commit inst/cubes.tgz -m 'Re-build inst/cubes.tgz from github actions'
                git push origin
            else
                echo "No changes detected."
            fi
