on: push

name: cube-compression

jobs:
  cube-compression:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Check for new changes to cube directory and commit
        run: |
            last_cube_commit=`git log -n 1 --pretty=format:%H -- inst/cubes.tgz`
            echo "git log:"
            git log -n 1 --pretty=format:%H -- inst/cubes.tgz
            echo "\ngit diff:"
            git diff --name-only --diff-filter=ADMR `git log -n 1 --pretty=format:%H -- inst/cubes.tgz` | grep inst/cubes/
            git diff --name-only --diff-filter=ADMR ${#last_cube_commit}
            echo "git diff with grep:"
            if git diff --name-only --diff-filter=ADMR `git log -n 1 --pretty=format:%H -- inst/cubes.tgz` | grep inst/cubes/
            then
                echo "Compressing"
            	make compress-fixtures
                git commit inst/cubes.tgz -m 'Re-build inst/cubes.tgz from github actions'
                git push origin
            else
                echo "No changes detected."
            fi
