on: push

name: mock-compression

jobs:
  mock-compression:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@master

      - name: Check for new changes to mocks directory and commit
        run: |
            last_compress_commit=`git log -n 1 --pretty=format:%H -- inst/mocks.tgz`
            files_changed=`git diff --name-only --diff-filter=ADMR ${last_compress_commit}`
            echo "Most recent commit that touched inst/mocks.tgz: "
            echo ${last_compress_commit}
            echo "Number of files changed since then: "
            echo ${files_changed} | wc -w
            if echo ${files_changed} | grep -q mocks/
            then
                echo "Compressing"
            	make compress-fixtures
                git commit inst/mocks.tgz -m 'Rebuild inst/mocks.tgz from github actions'
                git push origin
            else
                echo "No changes detected."
            fi
