on:
  push:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.TA_DA_ACCESS_NEW }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown

      - name: Decompress cubes
        run: Rscript 'dev-misc/compress-mocks.R'

      - name: Install package
        run: R CMD INSTALL .

      - name: Run pkgdown
        run: |
          git config --global user.email "rcrunch@crunch.io"
          git config --global user.name "rcrunch GitHub Action"
          bash 'pkgdown.sh'
